Repository siderolabs/omni, pull requests merged in 2024-09, with the labels that each got.

#598 chore: bump deps
  Makefile
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/backend/grpc/router/encoding.go
  internal/backend/runtime/omni/state_etcd.go
Labels: status/ok-to-test, status/ok-to-merge

#611 fix: calculate requested and connected machines in the `ClusterStatus`
  internal/backend/runtime/omni/controllers/omni/cluster_status.go
Labels: status/ok-to-test, status/ok-to-merge

#612 fix: filter readonly, CD and loop devices for 1.8
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/views/omni/Clusters/Management/ClusterMachineItem.vue
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_config_gen_options.go
Labels: status/ok-to-test, status/ok-to-merge

#614 release(v0.42.0-beta.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#615 fix: use YAML representation in `omnictl get`
  client/pkg/omnictl/get.go
Labels: status/ok-to-test, status/ok-to-merge

#619 fix: hide download audit log button if audit logs feature is disabled
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/methods/features.ts
  frontend/src/methods/index.ts
  frontend/src/views/omni/Overview/Overview.vue
  internal/e2e-tests/main_test.go
  internal/pkg/features/features.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#621 release(v0.42.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#626 release(v0.42.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#617 test: run infra integration tests against Talemu provider
  cmd/integration-test/pkg/tests/infra.go
  cmd/integration-test/pkg/tests/tests.go
  cmd/integration-test/root.go
  hack/test/integration.sh
Labels: status/ok-to-test, status/ok-to-merge

#625 docs: update omni template so docs are easier
  deploy/README.md
  deploy/compose.yaml
  deploy/env.template
Labels: status/ok-to-test, status/ok-to-merge

#628 fix: parse machine labels and extensions as slices in `omnictl download`
  client/pkg/omnictl/download.go
Labels: status/ok-to-test, status/ok-to-merge

#627 feat: allow specifying grpc tunnel option explicitly for install media
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_vtproto.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/siderolink.proto
  client/api/omni/specs/siderolink_vtproto.pb.go
  client/pkg/omni/resources/siderolink/connection_params.go
  client/pkg/omni/resources/siderolink/connection_params_test.go
  client/pkg/omnictl/download.go
  frontend/src/api/omni/management/management.pb.ts
  frontend/src/api/omni/specs/siderolink.pb.ts
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
  internal/backend/grpc/schematics.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge

#629 chore: bump default versions: Talos `1.7.6`, Kubernetes `1.30.5`
  client/pkg/constants/constants.go
  frontend/src/api/resources.ts
  hack/test/integration.sh
  internal/pkg/constants/versions.go
Labels: status/ok-to-test, status/ok-to-merge

#636 release(v0.42.2): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#633 fix: call deprovision only after the machine request status is deleted
  client/pkg/infra/controllers/provision.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
Labels: status/ok-to-test, status/ok-to-merge

#635 chore: drop machine class status and machine set pressure resources
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/machine_class_status.go
  client/pkg/omni/resources/omni/machine_set_required_machines.go
  client/pkg/omni/resources/omni/omni.go
  cmd/integration-test/pkg/tests/auth.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  internal/backend/runtime/omni/controllers/omni/machine_class_status.go
  internal/backend/runtime/omni/controllers/omni/machine_class_status_test.go
  internal/backend/runtime/omni/controllers/omni/machine_set.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
  internal/backend/runtime/omni/migration/compat.go
  internal/backend/runtime/omni/migration/deprecated_resources_test.go
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
Labels: status/ok-to-test, status/ok-to-merge

#637 release(v0.42.3): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#630 feat: support attaching machine sets to a machine request sets
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/machine_set.go
  client/pkg/template/internal/models/machineset.go
  client/pkg/template/operations/export.go
  client/pkg/template/operations/testdata/export/cluster-resources.yaml
  client/pkg/template/testdata/cluster-valid-bootstrapspec-resources.yaml
  client/pkg/template/testdata/cluster1-resources.yaml
  client/pkg/template/testdata/cluster2-resources.yaml
  client/pkg/template/testdata/cluster3-resources.yaml
  cmd/integration-test/pkg/tests/cluster.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/components/common/Button/TButtonGroup.vue
  frontend/src/methods/machineset.ts
  frontend/src/states/cluster-management/index.ts
  frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
  frontend/src/views/omni/Clusters/Management/ClusterMachineItem.vue
  frontend/src/views/omni/Clusters/Management/MachineSetConfig.vue
  frontend/test/unit/clusterManageState.spec.ts
  internal/backend/runtime/omni/audit/data.go
  internal/backend/runtime/omni/audit/hooks/hooks.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler_test.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge

#646 feat: make infra provider report back it's information: schema, name
  client/api/omni/specs/infra.pb.go
  client/api/omni/specs/infra.proto
  client/api/omni/specs/infra_vtproto.pb.go
  client/pkg/infra/infra.go
  client/pkg/infra/infra_test.go
  client/pkg/omni/resources/infra/infra.go
  client/pkg/omni/resources/infra/provider_status.go
  cmd/integration-test/pkg/tests/auth.go
  frontend/src/api/omni/specs/infra.pb.ts
  frontend/src/api/resources.ts
  internal/backend/runtime/omni/infraprovider/state_test.go
  internal/backend/runtime/omni/state_access.go
Labels: status/ok-to-test, status/ok-to-merge

#639 chore: fix capitalization of wireguard
  cmd/omni/main.go
  frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanelCondition.vue
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
  frontend/src/views/omni/Overview/Overview.vue
  hack/zstd-dict/data/machineconfig.tmpl.yaml
Labels: status/ok-to-merge

#648 test: fix the error message in infra test
  cmd/integration-test/pkg/tests/infra.go
Labels: status/ok-to-test, status/ok-to-merge

#649 feat: update Omni for Talos 1.8 machinery
  .kres.yaml
  Dockerfile
  client/go.mod
  client/go.sum
  client/pkg/omni/resources/omni/config_patch.go
  frontend/src/api/resources.ts
  frontend/src/components/common/CodeEditor/CodeEditor.vue
  frontend/src/schemas/config.schema.json
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#641 feat: integrate with Talos diagnostics
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/cluster_diagnostics.go
  client/pkg/omni/resources/omni/omni.go
  cmd/integration-test/pkg/tests/auth.go
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/components/common/List/TListItem.vue
  frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue
  frontend/src/views/cluster/ClusterMachines/ClusterMachines.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
  frontend/src/views/cluster/Nodes/NodeDiagnosticWarnings.vue
  frontend/src/views/cluster/Nodes/NodeOverview.vue
  frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanel.vue
  internal/backend/runtime/omni/controllers/omni/cluster_diagnostics.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
Labels: status/ok-to-test, status/ok-to-merge

#652 fix: support whitespaces in the label selectors
  client/pkg/cosi/labels/labels_test.go
  client/pkg/cosi/labels/lexer.go
Labels: status/ok-to-test, status/ok-to-merge
