Repository siderolabs/omni, pull requests merged in 2024-07, with the labels that each got.

#433 fix: properly clean up stale Talos gRPC backends
  Makefile
  internal/backend/grpc/router/router.go
  internal/backend/server.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#430 chore: add `go.work` file
  .gitignore
  .kres.yaml
  Makefile
  go.work
Labels: status/ok-to-test, status/ok-to-merge

#437 fix: enable etcd client keep-alives by default
  cmd/omni/main.go
  internal/backend/runtime/omni/state_etcd.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#438 fix: use proper permissions for cluster taint resource
  internal/backend/grpc/management.go
Labels: status/ok-to-test, status/ok-to-merge

#441 chore: add resource throughput metrics
  internal/backend/runtime/omni/state_metrics.go
Labels: status/ok-to-test, status/ok-to-merge

#443 fix: get rid of config patches for the maintenance configs
  cmd/integration-test/root.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go
  internal/backend/runtime/omni/controllers/omni/data/siderolink-config-patch.yaml
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch_test.go
  internal/backend/runtime/omni/controllers/omni/redacted_cluster_machine_config_test.go
  internal/backend/runtime/omni/migration/compat.go
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#435 fix: do not re-create peer on the remote addr change
  internal/backend/grpc/router/router.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#426 fix: add resource caches for missing resource types
  Dockerfile
  Makefile
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#425 release(v0.39.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#297 Update to compose deployment example to match and include tun requirement
  deploy/compose.yaml
  deploy/env.template
Labels: status/ok-to-merge

#445 fix: provide cached access to the state via Omni API
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/backend/grpc/grpc.go
  internal/backend/runtime/omni/omni.go
  internal/backend/server.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#451 fix: update Talos machine config schema to v1.7
  .kres.yaml
  Dockerfile
  frontend/src/schemas/config.schema.json
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#452 chore: bump deps
  go.mod
  go.sum
  internal/backend/grpc/router/router.go
  internal/backend/grpc/router/server.go
  internal/backend/grpc/router/talos_backend_test.go
Labels: status/ok-to-test, status/ok-to-merge

#453 fix: add missing `return err` in the maintenance config drop migration
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#454 fix: add finalizer on `MachineSetNode` resource in the controller
  internal/backend/runtime/omni/controllers/helpers/helpers.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_status.go
Labels: status/ok-to-test, status/ok-to-merge

#455 fix: do not expect LB to be healthy when scaling down workers
  internal/backend/runtime/omni/controllers/omni/internal/machineset/workers_handler.go
  internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go
Labels: status/ok-to-test, status/ok-to-merge

#456 fix: do not rely on `MachineStatus` updates when checking maintenance
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Labels: status/ok-to-test, status/ok-to-merge

#461 chore: rework auth.* keys, add `ctxstore` package
  cmd/omni/main.go
  internal/backend/grpc/configs_test.go
  internal/backend/grpc/management.go
  internal/backend/grpc/router/talos_backend.go
  internal/backend/k8sproxy/k8sproxy.go
  internal/backend/k8sproxy/middleware.go
  internal/backend/k8sproxy/middleware_test.go
  internal/backend/k8sproxy/multiplex.go
  internal/backend/k8sproxy/proxy.go
  internal/backend/runtime/omni/omni_test.go
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/virtual/state.go
  internal/backend/workloadproxy/accessvalidator.go
  internal/pkg/auth/accesspolicy/cluster.go
  internal/pkg/auth/actor/actor.go
  internal/pkg/auth/check.go
  internal/pkg/auth/check_test.go
  internal/pkg/auth/context.go
  internal/pkg/auth/handler/auth_config.go
  internal/pkg/auth/handler/handler_test.go
  internal/pkg/auth/handler/signature.go
  internal/pkg/auth/interceptor/auth_config.go
  internal/pkg/auth/interceptor/jwt.go
  internal/pkg/auth/interceptor/saml.go
  internal/pkg/auth/interceptor/signature.go
  internal/pkg/ctxstore/ctxstore.go
  internal/pkg/ctxstore/ctxstore_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-scaling, integration/e2e-backups, integration/e2e-upgrades, integration/e2e-short, integration/e2e-templates

#464 fix: use proper check for the machine set teardown flow
  internal/backend/runtime/omni/controllers/omni/machine_set_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go
Labels: status/ok-to-test, status/ok-to-merge

#465 release(v0.39.1): prepare release
  CHANGELOG.md
  go.mod
  go.sum
  hack/release.toml
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#467 fix: properly display icons on Safari browser
  frontend/src/components/common/Icon/TIcon.vue
Labels: status/ok-to-test, status/ok-to-merge

#471 chore: bump dependencies
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  go.work
Labels: status/ok-to-test, status/ok-to-merge

#472 fix: make image pre pull failure block the kubernetes update
  cmd/integration-test/pkg/tests/kubernetes.go
  internal/backend/runtime/omni/controllers/omni/internal/task/image/pulltask.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-upgrades

#468 feat: compute machineclass machine requirement (pressure)
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/labels.go
  client/pkg/omni/resources/omni/machine_class_status.go
  client/pkg/omni/resources/omni/machine_set_required_machines.go
  client/pkg/omni/resources/omni/omni.go
  cmd/integration-test/pkg/tests/auth.go
  frontend/src/api/omni/specs/omni.pb.ts
  internal/backend/runtime/omni/controllers/helpers/handler.go
  internal/backend/runtime/omni/controllers/omni/internal/mappers/mappers.go
  internal/backend/runtime/omni/controllers/omni/machine_class_status.go
  internal/backend/runtime/omni/controllers/omni/machine_class_status_test.go
  internal/backend/runtime/omni/controllers/omni/machine_cleanup.go
  internal/backend/runtime/omni/controllers/omni/machine_set.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
Labels: status/ok-to-test, status/ok-to-merge

#479 fix: use proper finalizer chain in the `MachineClassStatusController`
  internal/backend/runtime/omni/controllers/omni/machine_class_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
Labels: status/ok-to-test, status/ok-to-merge

#478 fix: properly update `ClusterMachineIdentity` resource
  internal/backend/runtime/omni/controllers/omni/cluster_machine_identity.go
Labels: status/ok-to-test, status/ok-to-merge

#481 test: enable Talemu tests
  .dockerignore
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .kres.yaml
  Dockerfile
  Makefile
  client/go.mod
  client/go.sum
  cmd/integration-test/pkg/clientconfig/clientconfig.go
  cmd/integration-test/pkg/tests/cluster.go
  cmd/integration-test/pkg/tests/talos.go
  cmd/integration-test/pkg/tests/template.go
  cmd/integration-test/pkg/tests/tests.go
  cmd/integration-test/root.go
  go.mod
  go.sum
  hack/test/integration.sh
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
Labels: status/ok-to-test, status/ok-to-merge

#436 feat: add support bundle download button to cluster overview
  client/api/omni/specs/virtual.pb.go
  client/api/omni/specs/virtual.proto
  client/api/omni/specs/virtual_vtproto.pb.go
  frontend/src/api/omni/specs/virtual.pb.ts
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/ProgressBar/ProgressBar.vue
  frontend/src/methods/auth.ts
  frontend/src/router/index.ts
  frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanel.vue
  frontend/src/views/omni/Modals/DownloadSupportBundle.vue
  internal/backend/runtime/omni/virtual/state.go
Labels: status/ok-to-test, status/ok-to-merge

#482 chore: bump deps
  frontend/bun.lockb
  frontend/package.json
  frontend/src/components/common/UserInfo/UserInfo.vue
  frontend/src/main.ts
  frontend/src/views/omni/Auth/Authenticate.vue
  hack/compose/docker-compose.yml
Labels: status/ok-to-test, status/ok-to-merge

#485 fix: preserve labels on the `MachineClass` when editing it in the UI
  frontend/src/views/omni/MachineClasses/MachineClass.vue
Labels: status/ok-to-test, status/ok-to-merge

#486 fix: do not allow deleting machine classes which are used anywhere
  internal/backend/runtime/omni/export_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge

#473 chore: add rotating log for audit data
  internal/backend/runtime/omni/audit/audit.go
  internal/backend/runtime/omni/audit/export_test.go
  internal/backend/runtime/omni/audit/log_file.go
  internal/backend/runtime/omni/audit/log_file_test.go
  internal/backend/runtime/omni/audit/testdata/concurrent/2012-01-01.jsonlog
  internal/backend/runtime/omni/audit/testdata/currentday/2012-01-01.jsonlog
  internal/backend/runtime/omni/audit/testdata/nextday/2012-01-01.jsonlog
  internal/backend/runtime/omni/audit/testdata/nextday/2012-01-02.jsonlog
  internal/backend/server.go
  internal/pkg/auth/role/role.go
  internal/pkg/pool/pool.go
Labels: status/ok-to-test, status/ok-to-merge

#487 chore: deprecate Talos 1.3
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/views/omni/Clusters/Management/ClusterCreate.vue
  frontend/src/views/omni/Modals/MaintenanceUpdate.vue
  internal/backend/runtime/omni/controllers/omni/versions.go
  internal/backend/runtime/omni/state_validation.go
  internal/pkg/constants/versions.go
Labels: status/ok-to-test, status/ok-to-merge

#488 chore: bump state-etcd module version
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#490 chore: bump kube-service-exposer version
  internal/backend/runtime/omni/controllers/omni/data/kube-service-exposer-config-patch.tmpl.yaml
Labels: status/ok-to-test, status/ok-to-merge

#493 release(v0.40.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#494 fix: do not recreate `MachineSetRequiredMachines` in the controller
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
Labels: status/ok-to-test, status/ok-to-merge

#449 feat: add cloud provider resources and role
  .kres.yaml
  Dockerfile
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_vtproto.pb.go
  client/api/omni/specs/cloud/cloud.pb.go
  client/api/omni/specs/cloud/cloud.proto
  client/api/omni/specs/cloud/cloud_vtproto.pb.go
  client/pkg/access/access.go
  client/pkg/access/serviceaccount.go
  client/pkg/access/serviceaccount_test.go
  client/pkg/client/management/management.go
  client/pkg/client/omni/omni.go
  client/pkg/omni/resources/auth/labels.go
  client/pkg/omni/resources/cloud/cloud.go
  client/pkg/omni/resources/cloud/machine_request.go
  client/pkg/omni/resources/cloud/machine_request_status.go
  client/pkg/omni/resources/omni/labels.go
  client/pkg/omni/resources/resources.go
  client/pkg/omnictl/serviceaccount.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/cli.go
  frontend/src/api/omni/management/management.pb.ts
  frontend/src/api/omni/specs/cloud/cloud.pb.ts
  frontend/src/api/resources.ts
  internal/backend/grpc/management.go
  internal/backend/grpc/serviceaccount.go
  internal/backend/runtime/omni/cloudprovider/cloudprovider.go
  internal/backend/runtime/omni/cloudprovider/state.go
  internal/backend/runtime/omni/cloudprovider/state_test.go
  internal/backend/runtime/omni/cloudprovider/validation.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state.go
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/validated/errors.go
  internal/frontend/frontend.go
  internal/pkg/auth/check.go
  internal/pkg/auth/role/role.go
Labels: status/ok-to-test, status/ok-to-merge

#498 fix: do not divide by 0 on the machine stats page
  frontend/src/views/omni/Machines/Machines.vue
Labels: status/ok-to-test, status/ok-to-merge

#497 test: run prometheus in tests and check metrics after talemu tests
  cmd/integration-test/pkg/tests/stats.go
  cmd/integration-test/pkg/tests/tests.go
  cmd/integration-test/root.go
  hack/compose/docker-compose.yml
  hack/compose/prometheus/prometheus.yml
  hack/test/integration.sh
Labels: status/ok-to-test, status/ok-to-merge

#496 release(v0.40.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge
