Repository siderolabs/omni, pull requests merged in 2024-05, with the labels that each got.

#186 feat: improve reliability of machine status snapshots
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/server.go
  internal/pkg/machinestatus/handler.go
  internal/pkg/machinestatus/handler_test.go
  internal/pkg/machinestatus/machinestatus.go
  internal/pkg/siderolink/adapter.go
  internal/pkg/siderolink/manager.go
  internal/pkg/siderolink/siderolink_test.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-scaling

#203 feat: add button to overview page to download partial machine config
  frontend/src/views/omni/Overview/Overview.vue
Labels: status/ok-to-test, status/ok-to-merge

#204 chore: bump `go-kubernetes` module
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#183 fix: do not allow adding ISO, PXE nodes running different Talos version
  client/pkg/omni/resources/omni/machine_status.go
  frontend/src/views/omni/Clusters/Management/ClusterCreate.vue
  frontend/src/views/omni/Clusters/Management/ClusterMachineItem.vue
  frontend/src/views/omni/Clusters/Management/ClusterScale.vue
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/state_validation.go
Labels: status/ok-to-test, status/ok-to-merge

#206 fix: invert the order of recent clusters
  frontend/package.json
  frontend/src/views/omni/Overview/Overview.vue
Labels: status/ok-to-test, status/ok-to-merge

#213 chore: use new Auth0 app for CI
  .secrets.yaml
  hack/generate-certs.example.yml
  hack/test/integration.sh
Labels: status/ok-to-test, status/ok-to-merge

#199 feat: automatically pick up extensions when upgrading Talos
  internal/backend/runtime/omni/controllers/omni/schematic_configuration.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration_test.go
Labels: status/ok-to-test, status/ok-to-merge

#209 fix: make `MachineSetNodeController` handle machinesets without clusters
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
Labels: status/ok-to-test, status/ok-to-merge

#216 feat: implement the UI for configuring extensions during cluster create
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/icons/IconExtensions.vue
  frontend/src/components/icons/IconExtensionsToggle.vue
  frontend/src/modal.ts
  frontend/src/states/cluster-management/index.ts
  frontend/src/views/omni/Clusters/Management/ClusterMachineItem.vue
  frontend/src/views/omni/Modals/ConfigPatchEdit.vue
  frontend/src/views/omni/Modals/CreateExtensions.vue
  frontend/src/views/omni/Modals/UpdateExtensions.vue
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
  internal/e2e-tests/main_test.go
Labels: status/ok-to-test, status/ok-to-merge

#218 feat: improve auth flow when user email is not verified
  frontend/src/views/omni/Auth/Authenticate.vue
  internal/pkg/auth/auth0/token.go
  internal/pkg/auth/interceptor/jwt.go
Labels: status/ok-to-test, status/ok-to-merge

#217 feat: unify admin settings under `Settings` page
  frontend/src/router/index.ts
  frontend/src/views/omni/Settings/BackupStorage.vue
  frontend/src/views/omni/Settings/Settings.vue
  frontend/src/views/omni/SideBar.vue
  frontend/src/views/omni/Users/Users.vue
  hack/test/integration.sh
  internal/e2e-tests/main_test.go
Labels: status/ok-to-test, status/ok-to-merge

#210 feat: allow setting some url params for api endpoint
  cmd/omni/main.go
  internal/pkg/config/config.go
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-merge

#225 release(v0.35.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#226 release(v0.35.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#231 fix: make search work on `NodeExtensions` page
  frontend/src/views/cluster/Nodes/NodeExtensions.vue
Labels: status/ok-to-test, status/ok-to-merge

#232 fix: get all attribute values from SAML ACS when adding user labels
  internal/backend/saml/saml.go
  internal/backend/saml/session.go
  internal/backend/saml/session_test.go
Labels: status/ok-to-test, status/ok-to-merge

#229 feat: implement the UI for adjusting machine sets update strategies
  frontend/src/components/common/Button/TButtonGroup.vue
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/TInput/TInput.vue
  frontend/src/modal.ts
  frontend/src/states/cluster-management/index.ts
  frontend/src/views/omni/Clusters/Management/MachineSetConfig.vue
  frontend/src/views/omni/Modals/ConfigPatchEdit.vue
  frontend/src/views/omni/Modals/MachineSetConfigEdit.vue
Labels: status/ok-to-test, status/ok-to-merge

#238 fix: do not try to audit machine which no longer has `MachineStatus`
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_etcd_audit.go
Labels: status/ok-to-test, status/ok-to-merge

#240 fix: do not block machine config updates if loadbalancer is down
  internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler.go
Labels: status/ok-to-test, status/ok-to-merge

#242 release(v0.35.1): prepare release
  CHANGELOG.md
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#247 fix: properly do rolling update on control plane nodes
  internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler_test.go
Labels: status/ok-to-merge

#251 fix: machine class edit page
  frontend/src/views/omni/MachineClasses/MachineClass.vue
Labels: status/ok-to-test, status/ok-to-merge

#255 chore: bump siderolink to 0.3.7
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#254 feat: warn about using `omnictl` version different from the backend
  client/pkg/omnictl/internal/access/client.go
Labels: status/ok-to-test, status/ok-to-merge

#256 fix: add the label when clicking outside of the input
  frontend/src/components/common/Labels/Labels.vue
  frontend/src/views/omni/ItemLabels/ItemLabels.vue
Labels: status/ok-to-test, status/ok-to-merge

#252 feat: implement labels completion for clusters and machines
  client/api/google/rpc/status.proto
  client/api/omni/specs/virtual.pb.go
  client/api/omni/specs/virtual.proto
  client/api/omni/specs/virtual_vtproto.pb.go
  client/pkg/omni/resources/virtual/labels_completion.go
  client/pkg/omni/resources/virtual/virtual.go
  cmd/integration-test/pkg/tests/auth.go
  frontend/src/api/google/rpc/code.proto
  frontend/src/api/google/rpc/status.proto
  frontend/src/api/omni/specs/virtual.pb.ts
  frontend/src/api/resources.ts
  frontend/src/components/common/List/TList.vue
  frontend/src/components/common/TInput/TInput.vue
  frontend/src/methods/labels.ts
  frontend/src/views/omni/Clusters/Clusters.vue
  frontend/src/views/omni/ItemLabels/ItemLabel.vue
  frontend/src/views/omni/ItemLabels/ItemLabels.vue
  frontend/src/views/omni/ItemLabels/LabelsInput.vue
  frontend/src/views/omni/MachineClasses/MachineClass.vue
  frontend/src/views/omni/Machines/Machines.vue
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/virtual/state.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#260 release(v0.36.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#262 chore: use large runners for ci
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .golangci.yml
  .kres.yaml
  Dockerfile
  Makefile
  client/.golangci.yml
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge

#264 chore: update Talos to 1.7.2 in the tests
  Makefile
  client/go.mod
  client/go.sum
  client/pkg/constants/constants.go
  frontend/src/api/resources.ts
  go.mod
  go.sum
  hack/test/integration.sh
  internal/backend/grpc/router/talos_backend_test.go
  internal/frontend/frontend.go
  internal/pkg/constants/versions.go
  internal/pkg/grpcutil/logger_test.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-upgrades

#265 release(v0.36.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#273 chore: always build frontend on BUILDPLATFORM
  Dockerfile
  Makefile
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge

#275 fix: get rid of duplicating label completion options
  frontend/src/views/omni/ItemLabels/LabelsInput.vue
Labels: status/ok-to-test, status/ok-to-merge

#274 feat: add dedicated patch pages for machines and cluster machines
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .golangci.yml
  Dockerfile
  Makefile
  client/.golangci.yml
  frontend/src/router/index.ts
  frontend/src/views/cluster/Config/ClusterPatches.vue
  frontend/src/views/cluster/Config/PatchEdit.vue
  frontend/src/views/cluster/Config/Patches.vue
  frontend/src/views/cluster/Nodes/NodePatches.vue
  frontend/src/views/cluster/Nodes/components/NodeDetailsTabs.vue
  frontend/src/views/omni/Machines/Machine.vue
  frontend/src/views/omni/Machines/MachineItem.vue
  frontend/src/views/omni/Machines/MachineLogs.vue
  frontend/src/views/omni/Machines/MachineLogsContainer.vue
  frontend/src/views/omni/Machines/MachinePatches.vue
  internal/backend/runtime/omni/controllers/omni/machine_set_etcd_audit_test.go
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge

#276 fix: use proper name for fetching existing extension configuration
  frontend/src/views/omni/Modals/UpdateExtensions.vue
Labels: status/ok-to-test, status/ok-to-merge

#278 feat: show service events on the node overview page
  frontend/src/components/common/Status/TStatus.vue
  frontend/src/constants/index.ts
  frontend/src/views/cluster/Nodes/NodeLogs.vue
  frontend/src/views/cluster/Nodes/NodeOverview.vue
  frontend/src/views/cluster/Nodes/NodeServiceEvents.vue
  frontend/src/views/cluster/SideBarNode.vue
  internal/backend/runtime/omni/controllers/omni/omni_test.go
Labels: status/ok-to-test, status/ok-to-merge

#279 chore: enable codecov and rekres
  .codecov.yml
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .kres.yaml
  Dockerfile
  Makefile
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge

#280 chore: run rekres
  .codecov.yml
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .kres.yaml
  Dockerfile
  Makefile
  frontend/package.json
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge

#286 fix: improve wording in authentication error messages
  internal/backend/grpc/auth.go
  internal/pkg/auth/interceptor/jwt.go
Labels: status/ok-to-test, status/ok-to-merge

#287 fix a typo in the on-prem installation link
  README.md
Labels: status/ok-to-merge

#296 fix: retry affiliate deletes
  internal/backend/runtime/omni/controllers/omni/cluster_machine_teardown.go
Labels: status/ok-to-test, status/ok-to-merge

#299 fix: ignore MachineStatus events timestamps as they're not reliable
  internal/pkg/machinestatus/handler.go
  internal/pkg/machinestatus/handler_test.go
Labels: status/ok-to-test, status/ok-to-merge

#305 fix: always generate siderolink connection config for all machines
  Makefile
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/siderolink/connection_params.go
  cmd/integration-test/pkg/tests/maintenance.go
  cmd/integration-test/pkg/tests/tests.go
  frontend/src/api/omni/specs/omni.pb.ts
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/data/maintenance-config-patch.yaml
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch_test.go
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-upgrades

#308 chore: bump default Talos version to 1.7.4
  client/pkg/constants/constants.go
  frontend/src/api/resources.ts
  hack/test/integration.sh
Labels: status/ok-to-test, status/ok-to-merge

#309 test: do not use epoch millis in service account names
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/cli.go
Labels: status/ok-to-test, status/ok-to-merge
