Repository siderolabs/omni, pull requests merged in 2024-03, with the labels that each got.

#5 fix: cleanup tearing down machine links without finalizers
  client/go.mod
  client/go.sum
  frontend/src/methods/machine.ts
  frontend/src/views/omni/Modals/MachineRemove.vue
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/machine_cleanup.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#50 fix: properly generate labels meta in the UI
  frontend/package.json
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Labels: status/ok-to-test, status/ok-to-merge

#2 refactor: convert `MachineSetStatus` controller to `QController`
  client/pkg/omni/resources/omni/labels.go
  cmd/omni-integration-test/pkg/tests/machines.go
  internal/backend/runtime/omni/controllers/helpers/helpers.go
  internal/backend/runtime/omni/controllers/helpers/helpers_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_identity.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_teardown.go
  internal/backend/runtime/omni/controllers/omni/cluster_status.go
  internal/backend/runtime/omni/controllers/omni/image_pull_status.go
  internal/backend/runtime/omni/controllers/omni/internal/configpatch/configpatch.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/control_planes_handler_test.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset_test.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/operations.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/operations_test.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/reconciliation_context.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/reconciliation_context_test.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/set.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler_test.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/tearing_down_handler.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/workers_handler.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/workers_handler_test.go
  internal/backend/runtime/omni/controllers/omni/internal/task/clustermachine/identity.go
  internal/backend/runtime/omni/controllers/omni/kubeconfig.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_upgrade_manifest_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_destroy_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/omni.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
  internal/backend/runtime/omni/controllers/omni/talosconfig.go
  internal/backend/runtime/omni/migration/helpers.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/backend/runtime/omni/omni.go
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#57 fix: add missing `v` prefix when looking up version in the image factory
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/talos_extensions.go
  internal/backend/runtime/omni/controllers/omni/talos_extensions_test.go
Labels: status/ok-to-test, status/ok-to-merge

#58 fix: add missing v prefix when looking up version in the image factory
  .conform.yaml
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/talos_extensions.go
  internal/backend/runtime/omni/controllers/omni/talos_extensions_test.go
Labels: status/ok-to-test, status/ok-to-merge

#60 release(v0.30.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#64 chore: bump Go, build arm64 container images, rekres
  .github/workflows/ci.yaml
  .kres.yaml
  Dockerfile
  Makefile
  client/go.mod
  go.mod
  go.sum
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge

#63 chore: drop integration binary from releases
  .github/workflows/ci.yaml
  .kres.yaml
  DEVELOPMENT.md
  Dockerfile
  Makefile
  cmd/integration-test/main.go
  cmd/integration-test/pkg/clientconfig/clientconfig.go
  cmd/integration-test/pkg/clientconfig/register_key_debug.go
  cmd/integration-test/pkg/clientconfig/register_key_no_debug.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/backup.go
  cmd/integration-test/pkg/tests/blocks.go
  cmd/integration-test/pkg/tests/cleanup.go
  cmd/integration-test/pkg/tests/cluster.go
  cmd/integration-test/pkg/tests/common.go
  cmd/integration-test/pkg/tests/config_patch.go
  cmd/integration-test/pkg/tests/extensions.go
  cmd/integration-test/pkg/tests/image.go
  cmd/integration-test/pkg/tests/kubernetes.go
  cmd/integration-test/pkg/tests/machines.go
  cmd/integration-test/pkg/tests/omniconfig.go
  cmd/integration-test/pkg/tests/rolling_update.go
  cmd/integration-test/pkg/tests/siderolink.go
  cmd/integration-test/pkg/tests/talos.go
  cmd/integration-test/pkg/tests/template.go
  cmd/integration-test/pkg/tests/testdata/cluster-1.tmpl.yaml
  cmd/integration-test/pkg/tests/testdata/cluster-2.tmpl.yaml
  cmd/integration-test/pkg/tests/tests.go
  cmd/integration-test/pkg/tests/utils.go
  cmd/integration-test/root.go
  hack/test/integration.sh
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge

#68 feat: preserve maintenance machine configs
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/constants/constants.go
  cmd/integration-test/pkg/tests/cluster.go
  cmd/integration-test/pkg/tests/maintenance.go
  cmd/integration-test/pkg/tests/tests.go
  frontend/src/api/omni/specs/omni.pb.ts
  hack/test/integration.sh
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch_test.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-upgrades

#71 fix: get rid of the issue with `MachineSets` stuck in `Reconfiguring`
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#73 release(v0.31.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#76 feat: add the context menu for copying the machine id
  frontend/src/components/common/ActionsBox/TActionsBox.vue
  frontend/src/views/common/NodeContextMenu.vue
  frontend/src/views/omni/Machines/MachineItem.vue
Labels: status/ok-to-test, status/ok-to-merge

#77 fix: properly handle upgrades for the machines with invalid schematics
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Labels: status/ok-to-test, status/ok-to-merge

#80 fix: fix error handling in image pre pull task
  internal/backend/runtime/omni/controllers/omni/internal/task/image/pulltask.go
Labels: status/ok-to-test, status/ok-to-merge

#70 feat: implement `omnictl support` command
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .kres.yaml
  Dockerfile
  Makefile
  client/api/common/common.proto
  client/api/common/omni.pb.go
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.pb.gw.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_grpc.pb.go
  client/api/omni/management/management_vtproto.pb.go
  client/api/omni/oidc/oidc.pb.go
  client/api/omni/resources/resources.pb.go
  client/api/omni/specs/auth.pb.go
  client/api/omni/specs/ephemeral.pb.go
  client/api/omni/specs/oidc.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/system.pb.go
  client/api/omni/specs/virtual.pb.go
  client/api/talos/machine/machine.pb.gw.go
  client/api/talos/machine/machine.proto
  client/go.mod
  client/go.sum
  client/pkg/client/management/management.go
  client/pkg/omnictl/support.go
  cmd/integration-test/pkg/tests/blocks.go
  cmd/integration-test/pkg/tests/talos.go
  frontend/src/api/omni/management/management.pb.ts
  go.mod
  go.sum
  internal/backend/grpc/grpc.go
  internal/backend/grpc/management.go
  internal/backend/grpc/support.go
  internal/backend/runtime/omni/controllers/omni/redacted_cluster_machine_config.go
  internal/backend/server.go
  internal/frontend/frontend.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#74 feat: compute schematic id only from the extensions
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/constants/constants.go
  client/pkg/omni/resources/omni/schematic.go
  cmd/integration-test/pkg/tests/talos.go
  cmd/omni/main.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
  hack/test/integration.sh
  internal/backend/grpc/export_test.go
  internal/backend/grpc/grpc.go
  internal/backend/grpc/grpc_test.go
  internal/backend/grpc/management.go
  internal/backend/grpc/schematics.go
  internal/backend/grpc/schematics_test.go
  internal/backend/imagefactory/client.go
  internal/backend/imagefactory/imagefactory.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/controllers/omni/internal/talos/schematic.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_link_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status_test.go
  internal/backend/runtime/omni/controllers/omni/talos_extensions.go
  internal/backend/runtime/omni/controllers/omni/talos_extensions_test.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/omni_test.go
  internal/backend/server.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-upgrades

#86 release(v0.32.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#85 feat: support setting extensions list in the cluster template
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/common/common.go
  client/pkg/omni/resources/omni/extensions_configuration.go
  client/pkg/omni/resources/omni/extensions_configuration_status.go
  client/pkg/omni/resources/omni/omni.go
  client/pkg/template/internal/models/cluster.go
  client/pkg/template/internal/models/machine.go
  client/pkg/template/internal/models/machineset.go
  client/pkg/template/internal/models/models.go
  client/pkg/template/operations/delete.go
  client/pkg/template/operations/export.go
  client/pkg/template/operations/testdata/export/cluster-resources.yaml
  client/pkg/template/operations/testdata/export/cluster-template.yaml
  client/pkg/template/order.go
  client/pkg/template/template.go
  client/pkg/template/testdata/cluster3-resources.yaml
  client/pkg/template/testdata/cluster3.yaml
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/talos.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/views/cluster/Overview/components/OverviewContent.vue
  internal/backend/grpc/support.go
  internal/backend/runtime/omni/controllers/omni/cluster.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine.go
  internal/backend/runtime/omni/controllers/omni/machine_set.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_link_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status_test.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#89 release(v0.32.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#96 docs: add screenshot and install link
  README.md
  docs/img/omni.png
Labels: status/ok-to-test, status/ok-to-merge
