Repository siderolabs/omni, pull requests merged in 2024-06, with the labels that each got.

#314 chore: bump deps
  .golangci.yml
  Dockerfile
  Makefile
  client/.golangci.yml
  client/api/common/omni.pb.go
  client/api/omni/management/management.pb.go
  client/api/omni/management/management_grpc.pb.go
  client/api/omni/oidc/oidc.pb.go
  client/api/omni/oidc/oidc_grpc.pb.go
  client/api/omni/resources/resources.pb.go
  client/api/omni/resources/resources_grpc.pb.go
  client/api/omni/specs/auth.pb.go
  client/api/omni/specs/ephemeral.pb.go
  client/api/omni/specs/oidc.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/system.pb.go
  client/api/omni/specs/virtual.pb.go
  client/go.mod
  client/go.sum
  client/pkg/client/client.go
  client/pkg/omnictl/output/yaml.go
  client/pkg/omnictl/serviceaccount.go
  client/pkg/omnictl/support.go
  client/pkg/template/operations/internal/utils/utils.go
  client/pkg/template/operations/status.go
  go.mod
  go.sum
  internal/backend/discovery/client.go
  internal/backend/grpc/grpc_test.go
  internal/backend/grpc/router/router.go
  internal/backend/grpc/router/talos_backend_test.go
  internal/backend/runtime/omni/state_etcd.go
  internal/e2e-tests/go.mod
  internal/e2e-tests/go.sum
  internal/frontend/frontend.go
  internal/pkg/auth/interceptor/signature_test.go
  internal/pkg/grpcutil/logger_test.go
  internal/pkg/siderolink/siderolink_test.go
Labels: status/ok-to-test, status/ok-to-merge

#317 chore: add renovate.json
  .github/renovate.json
Labels: status/ok-to-test, status/ok-to-merge

#316 feat: display more data on the node overview page
  client/pkg/constants/talos.go
  frontend/src/api/resources.ts
  frontend/src/components/common/Status/TStatus.vue
  frontend/src/constants/index.ts
  frontend/src/views/cluster/Nodes/NodeOverview.vue
  frontend/src/views/cluster/Nodes/NodeServiceEvents.vue
  frontend/src/views/cluster/Nodes/components/NodeConditions.vue
  internal/backend/runtime/cosi/cosi.go
Labels: status/ok-to-test, status/ok-to-merge

#311 fix: implement the controller for handling machine status snapshot
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  cmd/omni/main.go
  frontend/src/api/omni/specs/omni.pb.ts
  internal/backend/dns/service_test.go
  internal/backend/grpc/grpc_test.go
  internal/backend/runtime/omni/controllers/helpers/helpers.go
  internal/backend/runtime/omni/controllers/omni/cert_refresh_tick_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_bootstrap_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_endpoint_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_kubernetes_nodes_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_loadbalancer_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_test.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go
  internal/backend/runtime/omni/controllers/omni/image_pull_status_test.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/helpers.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/internal/task/runner.go
  internal/backend/runtime/omni/controllers/omni/internal/task/snapshot/snapshot.go
  internal/backend/runtime/omni/controllers/omni/key_pruner_test.go
  internal/backend/runtime/omni/controllers/omni/kubeconfig_test.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_node_audit_test.go
  internal/backend/runtime/omni/controllers/omni/loadbalancer_test.go
  internal/backend/runtime/omni/controllers/omni/machine_cleanup_test.go
  internal/backend/runtime/omni/controllers/omni/machine_extensions_test.go
  internal/backend/runtime/omni/controllers/omni/machine_labels_test.go
  internal/backend/runtime/omni/controllers/omni/machine_set_etcd_audit_test.go
  internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_link_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status_test.go
  internal/backend/runtime/omni/controllers/omni/machine_test.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch_test.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/controllers/omni/redacted_cluster_machine_config_test.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration_test.go
  internal/backend/runtime/omni/controllers/omni/secrets_test.go
  internal/backend/runtime/omni/controllers/omni/talos_extensions_test.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
  internal/backend/runtime/omni/controllers/omni/talosconfig_test.go
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/omni_test.go
  internal/backend/runtime/talos/clients_test.go
  internal/backend/server.go
  internal/pkg/auth/interceptor/signature_test.go
  internal/pkg/machinestatus/handler.go
  internal/pkg/machinestatus/handler_test.go
  internal/pkg/siderolink/logstorage_test.go
  internal/pkg/siderolink/siderolink_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#285 chore: rewrite `MachineStatus` to use `QController`
  cmd/integration-test/pkg/tests/talos.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/helpers.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/task.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_link_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status_test.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-scaling

#322 fix: read proper resource type in the `MachineStatusSnapshot`
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot_test.go
Labels: status/ok-to-test, status/ok-to-merge

#323 fix: properly generate machine config input versions in the migration
  internal/backend/runtime/omni/migration/helpers.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#325 feat: add Cache-Control header for head requests
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Labels: status/ok-to-merge

#321 fix: fix config generation failure due to secure boot status
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/cluster_machine_talos_version.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/views/cluster/Nodes/NodeOverview.vue
  frontend/src/views/omni/Machines/MachineItem.vue
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_teardown.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_config_gen_options.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration_test.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/migration/helpers.go
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#328 fix: properly set `Cache-Control` header
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Labels: status/ok-to-test, status/ok-to-merge

#331 fix: use proper routing on the config patch view and edit pages
  frontend/src/router/index.ts
  frontend/src/views/cluster/Config/PatchEdit.vue
  frontend/src/views/cluster/Config/Patches.vue
Labels: status/ok-to-test, status/ok-to-merge

#326 chore: migrate to Vite and Bun to build the frontend
  .dockerignore
  Dockerfile
  Makefile
  frontend/.gitignore
  frontend/babel.config.js
  frontend/bun.lockb
  frontend/bunfig.toml
  frontend/eslint.config.js
  frontend/favicon.ico
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/api/watch.ts
  frontend/src/components/TModal.vue
  frontend/src/components/common/CodeEditor/CodeEditor.vue
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/List/TList.vue
  frontend/src/components/common/OngoingTasks/OngoingTasks.vue
  frontend/src/components/common/SelectList/TSelectList.vue
  frontend/src/components/common/Watch/Watch.vue
  frontend/src/context.ts
  frontend/src/index.css
  frontend/src/main.ts
  frontend/src/methods/cluster.ts
  frontend/src/methods/index.ts
  frontend/src/methods/key.ts
  frontend/src/methods/logs.ts
  frontend/src/methods/time.ts
  frontend/src/router/index.ts
  frontend/src/states/cluster-management/index.ts
  frontend/src/vars/colors.js
  frontend/src/vars/colors.ts
  frontend/src/views/cluster/Backups/BackupsList.vue
  frontend/src/views/cluster/ClusterScoped.vue
  frontend/src/views/cluster/Config/PatchEdit.vue
  frontend/src/views/cluster/Manifest/Sync.vue
  frontend/src/views/cluster/Nodes/NodeMonitor.vue
  frontend/src/views/cluster/Nodes/NodeMounts.vue
  frontend/src/views/cluster/Nodes/NodeOverview.vue
  frontend/src/views/cluster/Nodes/NodeServiceEvents.vue
  frontend/src/views/cluster/Nodes/NodesList.vue
  frontend/src/views/cluster/Nodes/components/NodesItem.vue
  frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanel.vue
  frontend/src/views/cluster/Pods/components/TPodsItem.vue
  frontend/src/views/cluster/Pods/components/TPodsList.vue
  frontend/src/views/omni/Clusters/ClusterEtcdBackupCheckbox.vue
  frontend/src/views/omni/Machines/MachineLogsContainer.vue
  frontend/tailwind.config.ts
  frontend/test/setup.ts
  frontend/test/unit/clusterManageState.spec.ts
  frontend/test/unit/watch.spec.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/vue.config.js
  hack/compose/docker-compose.yml
  internal/frontend/frontend.go
Labels: status/ok-to-test, status/ok-to-merge

#330 fix: pass through the `talosctl -n` args if they cannot be resolved
  internal/backend/grpc/router/omni_backend.go
  internal/backend/grpc/router/resolve.go
  internal/backend/grpc/router/talos_backend.go
  internal/backend/grpc/router/talos_backend_test.go
Labels: status/ok-to-test, status/ok-to-merge

#337 chore: small fixes
  client/go.mod
  client/go.sum
  internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go
Labels: status/ok-to-test, status/ok-to-merge

#335 test: fix flaky test in `ClusterMachineConfigStatus` unit tests
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
Labels: status/ok-to-test, status/ok-to-merge

#334 test: fix a data race in `MachineStatusSnapshotController` unit tests
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot_test.go
Labels: status/ok-to-test, status/ok-to-merge

#338 fix: properly update the pulled images count if some images are skipped
  internal/backend/runtime/omni/controllers/omni/image_pull_status_test.go
  internal/backend/runtime/omni/controllers/omni/internal/task/image/pulltask.go
Labels: status/ok-to-test, status/ok-to-merge

#340 release(v0.37.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#333 feat: support authcode login in `kubectl oidc-login`
  Makefile
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_vtproto.pb.go
  client/api/omni/oidc/oidc.pb.go
  client/api/omni/oidc/oidc.proto
  client/api/omni/oidc/oidc_vtproto.pb.go
  client/pkg/client/management/management.go
  client/pkg/omnictl/kubeconfig.go
  frontend/src/api/omni/management/management.pb.ts
  frontend/src/api/omni/oidc/oidc.pb.ts
  frontend/src/views/omni/Auth/OIDC.vue
  frontend/src/views/omni/Clusters/ClusterEtcdBackupCheckbox.vue
  frontend/src/views/omni/Clusters/Management/ClusterCreate.vue
  internal/backend/grpc/management.go
  internal/backend/grpc/oidc.go
  internal/backend/oidc/internal/client/client.go
  internal/backend/runtime/kubernetes/kubernetes.go
  internal/backend/runtime/kubernetes/kubernetes_test.go
  internal/backend/runtime/kubernetes/testdata/oidc-kubeconfig3.yaml
Labels: status/ok-to-test, status/ok-to-merge

#336 fix: change Transport.Address field to Transport.Address method
  client/api/omni/management/management.pb.gw.go
  client/api/omni/oidc/oidc.pb.gw.go
  client/api/omni/resources/resources.pb.gw.go
  client/api/talos/machine/machine.pb.gw.go
  go.mod
  go.sum
  internal/backend/grpc/grpc.go
  internal/backend/grpc/router/router.go
  internal/backend/server.go
  internal/memconn/memconn.go
Labels: status/ok-to-test, status/ok-to-merge

#343 chore: upgrade github.com/containers/image to v5
  go.mod
  go.sum
  internal/pkg/image/image.go
Labels: status/ok-to-test, status/ok-to-merge

#346 fix: proper time adjustment to fix flaky TestEtcdManualBackup
  internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go
Labels: status/ok-to-test, status/ok-to-merge

#347 fix: ignore not found in the `MachineStatus` and `MachineStatusSnapshot`
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
Labels: status/ok-to-test, status/ok-to-merge

#348 feat: show pending config updates due to locked machine
  client/api/omni/management/management.pb.gw.go
  client/api/omni/oidc/oidc.pb.gw.go
  client/api/omni/resources/resources.pb.gw.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/api/talos/machine/machine.pb.gw.go
  client/pkg/omni/resources/omni/annotations.go
  client/pkg/template/operations/internal/statustree/helpers.go
  client/pkg/template/operations/internal/statustree/statustree.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/components/common/ActionsBox/TActionsBox.vue
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/Tooltip/Tooltip.vue
  frontend/src/components/icons/IconLockClosedToggle.vue
  frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue
  frontend/src/views/cluster/ClusterMachines/ClusterMachinePhase.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
  frontend/src/views/cluster/ClusterMachines/MachineSetPhase.vue
  frontend/src/views/omni/Clusters/ClusterItem.vue
  frontend/src/views/omni/Clusters/Clusters.vue
  frontend/src/views/omni/Clusters/Management/ClusterCreate.vue
  frontend/src/views/omni/Clusters/Management/ClusterScale.vue
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset_test.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/reconciliation_context.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler_test.go
Labels: status/ok-to-test, status/ok-to-merge

#351 chore: bump COSI runtime to 0.4.5
  client/go.mod
  client/go.sum
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#353 release(v0.37.2): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#350 feat: use circular buffer's new persistence option for machine logs
  cmd/omni/main.go
  internal/pkg/config/config.go
  internal/pkg/siderolink/loghandler.go
  internal/pkg/siderolink/loghandler_test.go
  internal/pkg/siderolink/logstorage.go
  internal/pkg/siderolink/logstorage_test.go
  internal/pkg/siderolink/machines.go
Labels: status/ok-to-test, status/ok-to-merge

#354 fix: properly detect `authcode-keyboard` oidc mode
  internal/backend/grpc/oidc.go
  internal/backend/oidc/external/external.go
  internal/backend/oidc/internal/client/client.go
Labels: status/ok-to-test, status/ok-to-merge

#355 fix: validate user email on creation
  frontend/src/notification.ts
  frontend/src/views/omni/Modals/UserCreate.vue
  internal/backend/runtime/omni/export_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge

#356 fix: ignore not found `ClusterMachine` in the migrations
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#357 fix: ignore not found `ClusterMachine` in the migrations
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#361 fix: properly generate maintenance config patches
  internal/backend/runtime/omni/controllers/omni/data/maintenance-config-patch.yaml
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_patch_test.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge

#363 release(v0.37.4): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#360 feat: provide a way to get admin `talosconfig` and `kubeconfig`
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_vtproto.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/client/management/management.go
  client/pkg/omni/resources/omni/cluster.go
  client/pkg/omni/resources/omni/cluster_taint.go
  client/pkg/omni/resources/omni/omni.go
  client/pkg/omnictl/kubeconfig.go
  client/pkg/omnictl/talosconfig.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/omni/main.go
  frontend/src/api/omni/management/management.pb.ts
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  internal/backend/grpc/configs_test.go
  internal/backend/grpc/grpc_test.go
  internal/backend/grpc/management.go
  internal/backend/grpc/support.go
  internal/backend/grpc/testdata/admin-kubeconfig.yaml
  internal/backend/runtime/helpers/helpers.go
  internal/backend/runtime/kubernetes/kubernetes.go
  internal/backend/runtime/kubernetes/kubernetes_test.go
  internal/backend/runtime/kubernetes/testdata/admin-kubeconfig.yaml
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/talosconfig_test.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#370 fix: properly delete the item from the cached items slice
  internal/backend/runtime/cosi/cosi.go
Labels: status/ok-to-test, status/ok-to-merge

#369 fix: properly delete the item from the cached items slice
  internal/backend/runtime/cosi/cosi.go
Labels: status/ok-to-test, status/ok-to-merge

#371 release(v0.37.5): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#372 fix: handle panics in Omni and Talos UI watches
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/talos/talos.go
Labels: status/ok-to-test, status/ok-to-merge

#364 feat: use the new domain scheme for exposed services
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/exposed_service.go
  cmd/omni/main.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/views/cluster/ExposedService/ExposedServiceSideBar.vue
  internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
  internal/backend/runtime/omni/omni.go
  internal/backend/server.go
  internal/backend/workloadproxy/handler.go
  internal/backend/workloadproxy/handler_test.go
  internal/backend/workloadproxy/workloadproxy.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#377 fix: use proper types in the machine status and snapshot controllers
  internal/backend/runtime/omni/controllers/helpers/helpers.go
  internal/backend/runtime/omni/controllers/omni/internal/task/runner.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
  internal/backend/runtime/omni/controllers/omni/machine_status_test.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
Labels: status/ok-to-test, status/ok-to-merge

#376 fix: skip invalid machines in `TalosUpgradeStatusController`
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
Labels: status/ok-to-test, status/ok-to-merge

#379 chore: add Akamai installation media
  internal/backend/runtime/omni/controllers/omni/installation_media.go
Labels: status/ok-to-merge

#382 fix: generate schematics with the extensions, meta and kernel args
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
Labels: status/ok-to-test, status/ok-to-merge

#383 fix: display descriptions when show description checkbox is clicked
  frontend/src/views/omni/Extensions/ExtensionsPicker.vue
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Labels: status/ok-to-test, status/ok-to-merge

#384 fix: use un-cached list in the `MachineSetNodeController`
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
Labels: status/ok-to-test, status/ok-to-merge

#385 fix: make `MachineSetNode` controller select only connected machines
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
Labels: status/ok-to-test, status/ok-to-merge

#386 release(v0.38.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#392 fix: do not use `time` namespace to parseDuration
  frontend/src/views/omni/Clusters/ClusterEtcdBackupCheckbox.vue
Labels: status/ok-to-test, status/ok-to-merge

#394 fix: use proper index for the Tooltip
  frontend/src/components/common/Tooltip/Tooltip.vue
Labels: status/ok-to-test, status/ok-to-merge

#398 release(v0.38.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#399 fix: do not use created time of the `ClusterMachineTalosVersion` in sort
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
Labels: status/ok-to-test, status/ok-to-merge

#401 fix: redo EtcdManualBackupShouldBeCreated
  cmd/integration-test/pkg/tests/backup.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-backups

#400 feat: provide cleaner UI for the machine sets/machines lists
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/methods/machineset.ts
  frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
Labels: status/ok-to-test, status/ok-to-merge

#389 feat: handle all goroutine panics gracefully
  .golangci.yml
  .kres.yaml
  Dockerfile
  Makefile
  client/.golangci.yml
  client/pkg/panichandler/panichandler.go
  client/pkg/panichandler/panichandler_test.go
  cmd/omni/main.go
  go.mod
  internal/backend/grpc/management.go
  internal/backend/grpc/resource.go
  internal/backend/grpc/support.go
  internal/backend/runtime/kubernetes/kubernetes.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup.go
  internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/crypt/crypt.go
  internal/backend/runtime/omni/controllers/omni/internal/task/clustermachine/identity.go
  internal/backend/runtime/omni/controllers/omni/internal/task/task.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_upgrade_manifest_status.go
  internal/backend/runtime/omni/external/state.go
  internal/backend/runtime/omni/external/state_test.go
  internal/backend/runtime/omni/pkg/check/etcd.go
  internal/backend/runtime/omni/state.go
  internal/backend/runtime/omni/state_etcd.go
  internal/backend/runtime/omni/state_etcd_election.go
  internal/backend/runtime/omni/virtual/computed.go
  internal/backend/runtime/omni/virtual/pkg/producers/kubernetes_usage.go
  internal/backend/runtime/proxy_runtime.go
  internal/backend/server.go
  internal/pkg/errgroup/errgroup.go
  internal/pkg/grpcutil/server.go
  internal/pkg/logreceiver/logreceiver.go
  internal/pkg/siderolink/manager.go
  internal/pkg/siderolink/siderolink_test.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#375 chore: migrate to oidc v3
  go.mod
  go.sum
  internal/backend/grpc/management.go
  internal/backend/grpc/oidc.go
  internal/backend/grpc/serviceaccount.go
  internal/backend/oidc/internal/client/client.go
  internal/backend/oidc/internal/models/auth_request.go
  internal/backend/oidc/internal/models/challenge.go
  internal/backend/oidc/internal/storage/authrequest/storage.go
  internal/backend/oidc/internal/storage/authrequest/storage_test.go
  internal/backend/oidc/internal/storage/keys/storage.go
  internal/backend/oidc/internal/storage/keys/storage_test.go
  internal/backend/oidc/internal/storage/storage.go
  internal/backend/oidc/internal/storage/token/mock_test.go
  internal/backend/oidc/internal/storage/token/storage.go
  internal/backend/oidc/internal/storage/token/storage_test.go
  internal/backend/oidc/oidc.go
  internal/backend/runtime/proxy_runtime.go
  internal/backend/server.go
Labels: status/ok-to-test, status/ok-to-merge

#403 chore: bump go to 1.22.4, rekres
  Dockerfile
  Makefile
  client/api/common/omni.pb.go
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.pb.gw.go
  client/api/omni/oidc/oidc.pb.go
  client/api/omni/oidc/oidc.pb.gw.go
  client/api/omni/resources/resources.pb.go
  client/api/omni/resources/resources.pb.gw.go
  client/api/omni/specs/auth.pb.go
  client/api/omni/specs/ephemeral.pb.go
  client/api/omni/specs/oidc.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/system.pb.go
  client/api/omni/specs/virtual.pb.go
  client/api/talos/machine/machine.pb.gw.go
  client/go.mod
Labels: status/ok-to-test, status/ok-to-merge

#393 chore: update runtime and go-api-signature modules
  client/go.mod
  client/go.sum
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#404 chore: replace append with slices pkg functions
  client/pkg/template/internal/models/list.go
  client/pkg/template/operations/delete.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#406 fix: use proper `z-index` for the tooltip component
  frontend/src/components/common/Tooltip/Tooltip.vue
Labels: status/ok-to-test, status/ok-to-merge

#407 fix: use proper `z-index` for the tooltip component
  frontend/src/components/common/Tooltip/Tooltip.vue
Labels: status/ok-to-test, status/ok-to-merge

#409 release(v0.38.1): prepare release
  .conform.yaml
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#408 fix: do better handling of small screens
  frontend/src/components/THeader/THeader.vue
  frontend/src/components/common/Button/TButton.vue
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/OngoingTasks/OngoingTasks.vue
  frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
Labels: status/ok-to-test, status/ok-to-merge

#412 chore: bump COSI runtime version, use its task runner
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/cluster_machine_identity.go
  internal/backend/runtime/omni/controllers/omni/image_pull_status.go
  internal/backend/runtime/omni/controllers/omni/internal/task/image/pulltask.go
  internal/backend/runtime/omni/controllers/omni/internal/task/runner.go
  internal/backend/runtime/omni/controllers/omni/internal/task/runner_test.go
  internal/backend/runtime/omni/controllers/omni/internal/task/task.go
  internal/backend/runtime/omni/controllers/omni/internal/task/task_test.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
Labels: status/ok-to-test, status/ok-to-merge

#410 feat: use tcp loadbalancer for exposed services
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/cluster_workload_proxy_status.go
  client/pkg/omni/resources/omni/omni.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/omni/main.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  internal/backend/grpc/grpc_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status_metrics.go
  internal/backend/runtime/omni/controllers/omni/cluster_status_metrics.go
  internal/backend/runtime/omni/controllers/omni/cluster_workload_proxy_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_workload_proxy_status_test.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup.go
  internal/backend/runtime/omni/controllers/omni/kubeconfig.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_node_audit.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/talosconfig.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/omni_test.go
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/talosconfig_test.go
  internal/backend/server.go
  internal/backend/workloadproxy/reconciler.go
  internal/backend/workloadproxy/reconciler_test.go
  internal/backend/workloadproxy/serviceregistry.go
  internal/backend/workloadproxy/serviceregistry_test.go
Labels: status/ok-to-test, status/ok-to-merge

#415 release(v0.38.2): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#416 feat: show `N/∞` in the machine set if unlim allocation policy is used
  frontend/src/components/TModal.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
  frontend/src/views/omni/Modals/UpdateKubernetes.vue
  frontend/src/views/omni/Modals/UpdateTalos.vue
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#417 feat: read real IP from the provision API gRPC requests
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/siderolink.proto
  client/api/omni/specs/siderolink_vtproto.pb.go
  frontend/src/api/omni/specs/siderolink.pb.ts
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge

#418 chore: bump dependencies
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/etcdbackup/store/s3store.go
Labels: status/ok-to-test, status/ok-to-merge

#420 feat: add `Equinix metal` option in the download installation media
  internal/backend/runtime/omni/controllers/omni/installation_media.go
Labels: status/ok-to-test, status/ok-to-merge

#421 fix: allow changing machine set node mgmt mode if it has no nodes
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge

#428 fix: add resource caches for missing resource types
  Makefile
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge

#429 release(v0.38.3): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge
