Repository siderolabs/omni, pull requests merged in 2024-10, with the labels that each got.

#665 chore: add a way to get provider data in the infra provider
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .github/workflows/e2e-workload-proxy-cron.yaml
  client/pkg/infra/controllers/provision.go
  client/pkg/infra/provision/context.go
  client/pkg/infra/provision/errors.go
  frontend/src/components/common/Form/ContentWrapper.vue
  internal/backend/runtime/omni/controllers/omni/machine_provision.go
  internal/backend/runtime/omni/controllers/omni/machine_request_set_status.go
Labels: status/ok-to-test, status/ok-to-merge

#672 fix: ignore parse errors in the log parser
  frontend/src/methods/logs.ts
Labels: status/ok-to-test, status/ok-to-merge

#673 chore: refactor code
  cmd/integration-test/pkg/tests/cluster.go
  cmd/omni/main.go
  internal/backend/grpc/grpc.go
  internal/backend/grpc/management.go
  internal/backend/grpc/router/router.go
  internal/backend/proxy_server.go
  internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/crypt/crypt.go
  internal/backend/runtime/omni/controllers/omni/internal/kubernetes/kubernetes_test.go
  internal/backend/server.go
  internal/memconn/memconn.go
  internal/pkg/resetable/closer.go
  internal/pkg/resetable/closer_test.go
  internal/pkg/xcontext/xcontext.go
Labels: status/ok-to-test, status/ok-to-merge

#674 chore: set `peer.address` to inform about IP status
  internal/pkg/grpcutil/logger.go
Labels: status/ok-to-test, status/ok-to-merge

#671 fix: filter requests in the infra provision controller
  .github/workflows/ci.yaml
  .kres.yaml
  Dockerfile
  Makefile
  client/api/omni/specs/infra.pb.go
  client/api/omni/specs/infra.proto
  client/api/omni/specs/infra_vtproto.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/siderolink.proto
  client/api/omni/specs/siderolink_vtproto.pb.go
  client/pkg/client/management/management.go
  client/pkg/infra/controllers/provision.go
  client/pkg/infra/infra_test.go
  client/pkg/infra/provision/context.go
  client/pkg/omni/resources/siderolink/connection_params.go
  client/pkg/omni/resources/siderolink/connection_params_test.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/cluster.go
  cmd/integration-test/pkg/tests/tests.go
  cmd/integration-test/root.go
  frontend/src/api/omni/specs/infra.pb.ts
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/omni/specs/siderolink.pb.ts
  frontend/src/views/omni/MachineClasses/MachineClass.vue
  frontend/src/views/omni/MachineClasses/MachineTemplate.vue
  go.mod
  internal/backend/grpc/grpc.go
  internal/backend/grpc/router/router.go
  internal/backend/grpc/router/talos_backend.go
  internal/backend/runtime/omni/audit/walk.go
  internal/backend/runtime/omni/controllers/omni/machine_provision.go
  internal/backend/runtime/omni/controllers/omni/machine_request_set_status.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
  internal/backend/runtime/omni/testdata/infra.json
  internal/backend/server.go
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge

#675 fix: get proper IP from peer metadata
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/siderolink.proto
  internal/backend/logging/handler.go
  internal/backend/server.go
  internal/pkg/grpcutil/logger.go
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge

#679 release(v0.43.0-beta.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#680 feat: display pending machine requests in the machine sets
  .github/workflows/ci.yaml
  .kres.yaml
  client/api/omni/specs/infra.pb.go
  client/api/omni/specs/infra.proto
  client/api/omni/specs/infra_vtproto.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/infra/controllers/provision.go
  client/pkg/omni/resources/omni/cluster_machine_request_status.go
  client/pkg/omni/resources/omni/machine_request_set_pressure.go
  client/pkg/omni/resources/omni/omni.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/blocks.go
  cmd/integration-test/pkg/tests/cluster.go
  cmd/integration-test/pkg/tests/infra.go
  cmd/integration-test/pkg/tests/talos.go
  cmd/integration-test/pkg/tests/tests.go
  frontend/bun.lockb
  frontend/package.json
  frontend/src/api/omni/specs/infra.pb.ts
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/components/common/Status/TStatus.vue
  frontend/src/components/icons/IconHeaderDropdownLoading.vue
  frontend/src/constants/index.ts
  frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue
  frontend/src/views/cluster/ClusterMachines/MachineRequest.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
  frontend/src/views/omni/Clusters/ClusterStatus.vue
  frontend/src/views/omni/MachineClasses/MachineClass.vue
  frontend/src/views/omni/MachineClasses/MachineTemplate.vue
  frontend/src/views/omni/MachineClasses/ProviderConfig.vue
  internal/backend/runtime/omni/controllers/omni/cluster_machine_request_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_request_status_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_status.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/status_handler.go
  internal/backend/runtime/omni/controllers/omni/machine_provision.go
  internal/backend/runtime/omni/controllers/omni/machine_provision_test.go
  internal/backend/runtime/omni/controllers/omni/machine_request_set_pressure.go
  internal/backend/runtime/omni/controllers/omni/machine_request_set_pressure_test.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#682 release(v0.43.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#686 fix: properly return error from `config.Init`
  client/pkg/omnictl/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#681 chore: move from Codec to CodecV2
  client/go.mod
  client/go.sum
  client/pkg/client/client.go
  client/pkg/client/encoding.go
  cmd/acompat/acompat.go
  cmd/integration-test/main.go
  cmd/integration-test/pkg/root.go
  cmd/omni/cmd/cmd.go
  cmd/omni/main.go
  go.mod
  go.sum
  hack/zstd-dict/go.mod
  hack/zstd-dict/go.sum
  internal/backend/grpc/router/encoding.go
  internal/backend/grpc/router/router.go
  internal/backend/grpc/router/server.go
  internal/backend/grpc/router/talos_backend_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#152 add basic helm chart
  deploy/helm/README.md
  deploy/helm/omni/.helmignore
  deploy/helm/omni/Chart.yaml
  deploy/helm/omni/templates/_helpers.tpl
  deploy/helm/omni/templates/deployment.yaml
  deploy/helm/omni/templates/generic-device-plugin.yaml
  deploy/helm/omni/templates/service.yaml
  deploy/helm/omni/values.yaml
Labels: status/ok-to-merge

#688 chore: remove `ip_address` field from audit log `session`
  internal/backend/runtime/omni/audit/data.go
  internal/backend/runtime/omni/audit/log_file_test.go
  internal/backend/runtime/omni/audit/testdata/concurrent/2012-01-01.jsonlog
  internal/backend/runtime/omni/audit/testdata/currentday/2012-01-01.jsonlog
  internal/backend/runtime/omni/audit/testdata/log/2012-01-01.jsonlog
  internal/backend/runtime/omni/audit/testdata/nextday/2012-01-01.jsonlog
  internal/backend/runtime/omni/audit/testdata/nextday/2012-01-02.jsonlog
  internal/pkg/grpcutil/audit.go
Labels: status/ok-to-test, status/ok-to-merge

#689 fix: introduce timeout in the etcd healthchecks in the machine set ctrl
  internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset.go
Labels: status/ok-to-test, status/ok-to-merge

#690 release(v0.43.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#687 feat: support insecure localhost infra provider access mode
  .github/workflows/ci.yaml
  .kres.yaml
  Dockerfile
  Makefile
  client/pkg/access/serviceaccount.go
  client/pkg/access/validate.go
  client/pkg/client/client.go
  client/pkg/client/omni/omni.go
  client/pkg/client/options.go
  client/pkg/constants/constants.go
  client/pkg/infra/controllers/provision.go
  client/pkg/infra/infra.go
  cmd/integration-test/pkg/clientconfig/clientconfig.go
  cmd/integration-test/pkg/root.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/blocks.go
  cmd/integration-test/pkg/tests/cluster.go
  cmd/integration-test/pkg/tests/tests.go
  cmd/omni/cmd/cmd.go
  internal/backend/grpc/serviceaccount.go
  internal/backend/server.go
  internal/pkg/auth/actor/actor.go
  internal/pkg/auth/serviceaccount/serviceaccount.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#692 fix: build arm64 integration tests executable
  .github/workflows/ci.yaml
  .kres.yaml
  Dockerfile
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#693 fix: do not build acompat docker image
  .github/workflows/ci.yaml
  .kres.yaml
  Dockerfile
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#695 fix: do not set empty initial labels in the UI
  client/pkg/infra/controllers/provision.go
  frontend/src/views/omni/MachineClasses/MachineClass.vue
Labels: status/ok-to-test, status/ok-to-merge

#696 fix: fetch Talos version from the image factory
  internal/backend/runtime/omni/controllers/omni/versions.go
Labels: status/ok-to-test, status/ok-to-merge

#697 fix: filter block devices with UNKNOWN type
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
Labels: status/ok-to-test, status/ok-to-merge

#698 chore: bump dependencies
  Dockerfile
  Makefile
  client/go.mod
  client/go.sum
  frontend/bun.lockb
  frontend/package.json
  frontend/src/components/common/Notification/TNotification.vue
  frontend/src/methods/auth.ts
  frontend/src/methods/cluster.ts
  frontend/src/methods/index.ts
  frontend/src/methods/key.ts
  frontend/src/methods/logs.ts
  frontend/src/methods/machine.ts
  frontend/src/views/omni/Auth/Authenticate.vue
  go.mod
  go.sum
  hack/compose/docker-compose.yml
  hack/test/integration.sh
Labels: status/ok-to-test, status/ok-to-merge

#699 fix: do not read Talos versions from the image registry ever
  internal/backend/runtime/omni/controllers/omni/versions.go
Labels: status/ok-to-test, status/ok-to-merge

#700 fix: use proper selectors in the MachineClass create UI
  frontend/src/views/omni/MachineClasses/MachineClass.vue
Labels: status/ok-to-test, status/ok-to-merge

#701 chore: do not audit log `GET` requests to k8s
  go.work
  internal/backend/k8sproxy/middleware.go
  internal/backend/runtime/omni/audit/audit.go
  internal/backend/runtime/omni/audit/data.go
Labels: status/ok-to-test, status/ok-to-merge

#702 fix: properly show the current manifests in the bootstrap manifest sync
  frontend/src/views/cluster/Manifest/Sync.vue
Labels: status/ok-to-test, status/ok-to-merge

#708 release(v0.43.2): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#709 fix: remove `MaintenanceConfigPatchController` finalizers
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#710 release(v0.43.3): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#704 feat: automatically resolve cluster in `talosctl` calls
  .golangci.yml
  cmd/integration-test/pkg/tests/talos.go
  internal/backend/dns/service.go
  internal/backend/dns/service_test.go
  internal/backend/grpc/router/resolve.go
  internal/backend/grpc/router/router.go
Labels: status/ok-to-test, status/ok-to-merge

#703 feat: reset machine when it's removed from Omni
  internal/backend/runtime/omni/controllers/omni/machine_teardown.go
  internal/backend/runtime/omni/omni.go
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#718 fix: make web UI show favicon
  .dockerignore
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge
