Repository siderolabs/omni, pull requests merged in 2025-06, with the labels that each got.

#1240 fix: bump inmem COSI state history capacity
  internal/backend/runtime/omni/state.go
Labels: status/ok-to-test, status/ok-to-merge

#1247 fix: display unknown power state correctly on the machines screen
  frontend/src/views/omni/Machines/MachineItem.vue
Labels: status/ok-to-test, status/ok-to-merge

#1248 fix: check config patch creation time as well as updated on orphan check
  internal/backend/runtime/omni/controllers/omni/config_patch_cleanup.go
Labels: status/ok-to-test, status/ok-to-merge

#1253 fix: use `0.0.0.0:8095` as the default bind endpoint for Kubernetes
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#1254 fix: fix exposed service prefix conflict resolution
  internal/backend/runtime/omni/controllers/helpers/helpers.go
  internal/backend/runtime/omni/controllers/omni/internal/exposedservice/reconciler.go
  internal/backend/runtime/omni/controllers/omni/internal/exposedservice/reconciler_test.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-workload-proxy

#1260 release(v0.51.0-beta.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#1261 fix: remove `required` config validation from k8s proxy cert and key
  internal/pkg/config/config_test.go
  internal/pkg/config/services.go
  internal/pkg/config/testdata/config-no-tls-certs.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1262 fix: do more fixes on config backward-compatibility
  cmd/omni/cmd/cmd.go
  internal/pkg/config/config.go
  internal/pkg/config/logs.go
  internal/pkg/config/storage.go
Labels: status/ok-to-test, status/ok-to-merge

#1270 release(v0.51.0-beta.2): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1273 release(v0.51.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1282 test: save a support bundle when a test suite has failed
  internal/backend/runtime/omni/controllers/omni/infra_machine.go
  internal/integration/blocks_test.go
  internal/integration/cluster_test.go
  internal/integration/integration_test.go
  internal/integration/suites_test.go
  internal/integration/talos_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1287 docs: add guide for development on darwin
  DEVELOPMENT.md
Labels: status/ok-to-test, status/ok-to-merge

#1281 test: test updating from old Omni version to the current
  .github/workflows/ci.yaml
  .github/workflows/e2e-omni-upgrade-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
  hack/test/integration.sh
  internal/integration/integration_test.go
  internal/integration/omni_upgrade_test.go
  internal/integration/suites_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1283 feat: allow encoding the machine request ID into the join tokens
  client/api/omni/specs/infra.pb.go
  client/api/omni/specs/infra.proto
  client/api/omni/specs/infra_vtproto.pb.go
  client/pkg/infra/controllers/provision.go
  client/pkg/infra/infra.go
  client/pkg/infra/infra_test.go
  client/pkg/infra/options.go
  client/pkg/infra/provision/context.go
  client/pkg/omni/resources/infra/infra.go
  client/pkg/omni/resources/infra/machine_registration.go
  client/pkg/omni/resources/siderolink/connection_params.go
  client/pkg/omni/resources/siderolink/connection_params_test.go
  client/pkg/omni/resources/system/resource_labels.go
  frontend/src/api/omni/specs/infra.pb.ts
  frontend/src/api/resources.ts
  internal/backend/runtime/omni/controllers/omni/infra_machine_registration.go
  internal/backend/runtime/omni/controllers/omni/labels_extractor.go
  internal/backend/runtime/omni/controllers/omni/machine.go
  internal/backend/runtime/omni/controllers/omni/machine_extensions.go
  internal/backend/runtime/omni/controllers/omni/machine_request_link.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
  internal/backend/runtime/omni/infraprovider/state.go
  internal/backend/runtime/omni/infraprovider/state_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_etcd.go
  internal/backend/runtime/omni/state_etcd_election.go
  internal/backend/runtime/omni/state_etcd_election_test.go
  internal/pkg/siderolink/provision.go
Labels: status/ok-to-test, status/ok-to-merge

#1288 fix: correctly detect installation status for bare-metal machines
  frontend/src/views/omni/Clusters/Management/ClusterCreate.vue
  frontend/src/views/omni/Clusters/Management/ClusterScale.vue
  frontend/src/views/omni/Machines/MachineItem.vue
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/integration/omni_upgrade_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1292 feat: support setting custom name ID format in SAML metadata
  client/api/omni/specs/auth.pb.go
  client/api/omni/specs/auth.proto
  client/api/omni/specs/auth_vtproto.pb.go
  cmd/omni/cmd/cmd.go
  frontend/src/api/omni/specs/auth.pb.ts
  frontend/src/api/resources.ts
  internal/backend/saml/saml.go
  internal/pkg/auth/config.go
  internal/pkg/config/auth.go
Labels: status/ok-to-test, status/ok-to-merge
