Repository siderolabs/omni, pull requests merged in 2025-09, with the labels that each got.

#1497 fix: copy buttons on omni home page
  frontend/src/views/omni/Home/HomeGeneralInformation.vue
  frontend/src/views/omni/Modals/NodeDestroyCancel.vue
Labels: status/ok-to-test, status/ok-to-merge

#1498 release(v1.1.3): prepare release
  CHANGELOG.md
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#1475 feat: support Userpilot reports
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/api/omni/specs/virtual.pb.go
  client/api/omni/specs/virtual.proto
  client/api/omni/specs/virtual_vtproto.pb.go
  cmd/omni/cmd/cmd.go
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/omni/specs/virtual.pb.ts
  frontend/src/methods/auth.ts
  frontend/src/methods/features.ts
  frontend/src/router/index.ts
  internal/backend/runtime/omni/virtual/state.go
  internal/frontend/handler.go
  internal/pkg/config/config.go
  internal/pkg/features/features.go
Labels: status/ok-to-test, status/ok-to-merge

#1500 chore: improve tbutton typings
  frontend/src/components/common/Button/IconButton.vue
  frontend/src/components/common/Button/TButton.vue
Labels: status/ok-to-test, status/ok-to-merge

#1505 fix: console warning about invalid watch value
  frontend/src/methods/auth.ts
  frontend/src/views/common/NodeContextMenu.vue
Labels: status/ok-to-test, status/ok-to-merge

#1513 fix: route resizing issue
  frontend/src/App.vue
  frontend/src/views/cluster/Nodes/NodeDetails.vue
  frontend/src/views/omni/Machines/Machine.vue
  frontend/src/views/omni/Settings/Settings.vue
Labels: status/ok-to-test, status/ok-to-merge

#1515 fix: route size on login and machine classes
  frontend/src/views/omni/Auth/Authenticate.vue
  frontend/src/views/omni/MachineClasses/MachineClass.vue
  frontend/src/views/omni/MachineClasses/MachineClasses.vue
Labels: status/ok-to-test, status/ok-to-merge

#1527 feat: implement cluster locking
  client/pkg/omni/resources/omni/annotations.go
  client/pkg/omnictl/cluster/cluster.go
  client/pkg/omnictl/cluster/machine.go
  frontend/src/api/resources.ts
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/methods/cluster.ts
  frontend/src/views/cluster/Overview/components/OverviewContent.vue
  frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanel.vue
  frontend/src/views/omni/Clusters/ClusterItem.vue
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_status.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_set_status_test.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status_test.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
  internal/integration/kubernetes_test.go
  internal/integration/talos_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1542 release(v1.1.4): prepare release
  CHANGELOG.md
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#1509 chore: remove the usage of --input-dir flag in tests
  hack/test/integration.sh
Labels: status/ok-to-test, status/ok-to-merge

#1556 feat: support generating join configs with searching join tokens by name
  client/pkg/omnictl/jointoken.go
Labels: status/ok-to-test, status/ok-to-merge

#1557 fix: home general info error & loading
  frontend/src/views/omni/Home/HomeContent.vue
  frontend/src/views/omni/Home/HomeGeneralInformation.vue
Labels: status/ok-to-test, status/ok-to-merge

#1555 fix: create join token modal margin
  frontend/src/views/omni/Modals/JoinTokenCreate.vue
Labels: status/ok-to-test, status/ok-to-merge

#1569 feat: abort ongoing cluster import process
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-cluster-import-cron.yaml
  .github/workflows/e2e-forced-removal-cron.yaml
  .github/workflows/e2e-omni-upgrade-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-short-secureboot-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .github/workflows/e2e-workload-proxy-cron.yaml
  .kres.yaml
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.pb.gw.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_grpc.pb.go
  client/api/omni/management/management_vtproto.pb.go
  client/pkg/client/management/management.go
  client/pkg/omni/resources/omni/labels.go
  client/pkg/omnictl/cluster/import.go
  frontend/src/api/omni/management/management.pb.ts
  frontend/src/api/resources.ts
  hack/test/wipe-a-vm.sh
  internal/backend/grpc/configs_test.go
  internal/backend/grpc/management.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_status.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/machineset.go
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/integration/cluster_test.go
  internal/integration/common_test.go
  internal/integration/integration_test.go
  internal/integration/machines_test.go
  internal/integration/suites_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-cluster-import

#1565 feat: implement user consent form for the `UserPilot`
  frontend/src/App.vue
  frontend/src/components/common/UserConsent/UserConsent.vue
  frontend/src/methods/auth.ts
  frontend/src/methods/features.ts
Labels: status/ok-to-test, status/ok-to-merge

#1580 fix: fix switch user button for Auth0
  frontend/src/views/omni/Auth/Authenticate.vue
Labels: status/ok-to-test, status/ok-to-merge

#1584 chore: strip comments from generated ClusterMachineConfig
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1577 release(1.2.0-beta.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1600 chore: colocate tests with their tested components
  .dockerignore
  Dockerfile
  frontend/eslint.config.ts
  frontend/src/api/watch.spec.ts
  frontend/src/methods/cluster.spec.ts
  frontend/src/states/cluster-management.spec.ts
  frontend/src/states/cluster-management.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.vitest.json
Labels: status/ok-to-test, status/ok-to-merge

#1603 test: including query string for saml login
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/grpc.ts
  frontend/src/api/options.ts
  frontend/src/api/watch.spec.ts
  frontend/src/components/common/CodeEditor/CodeEditor.vue
  frontend/src/methods/key.ts
  frontend/src/methods/logs.ts
  frontend/src/views/cluster/Nodes/NodeMonitor.vue
  frontend/src/views/cluster/Nodes/components/NodesMonitorChart.vue
  frontend/src/views/omni/Auth/Authenticate.spec.ts
  frontend/tsconfig.node.json
  frontend/tsconfig.vitest.json
  frontend/vite.config.ts
  frontend/vitest.setup.ts
Labels: status/ok-to-test, status/ok-to-merge

#1605 test: introduce msw to mock api calls
  .dockerignore
  Dockerfile
  frontend/msw/index.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/watch.spec.ts
  frontend/tsconfig.node.json
  frontend/tsconfig.vitest.json
  frontend/vitest.setup.ts
Labels: status/ok-to-test, status/ok-to-merge

#1612 fix: add `oidc-redirect-url` arg to the generated kubeconfigs
  hack/release.toml
  internal/backend/grpc/management.go
Labels: status/ok-to-test, status/ok-to-merge

#1620 refactor: simplify tslidedownwrapper
  frontend/src/components/common/List/ListItemBox.vue
  frontend/src/components/common/List/TListItem.vue
  frontend/src/components/common/SlideDownWrapper/TSlideDownWrapper.vue
  frontend/src/views/cluster/Pods/components/TPodsItem.vue
Labels: status/ok-to-test, status/ok-to-merge

#1628 refactor: remove listitembox
  frontend/src/components/common/List/ListItemBox.vue
  frontend/src/views/omni/Settings/InfraProviders.vue
Labels: status/ok-to-test, status/ok-to-merge

#1642 fix(frontend): adjust spacing of items in infraproviders
  frontend/src/components/common/Status/TStatus.vue
  frontend/src/views/omni/Settings/InfraProviders.vue
Labels: status/ok-to-test, status/ok-to-merge

#1656 release(v1.2.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e
