Repository siderolabs/omni, pull requests merged in 2025-02, with the labels that each got.

#897 fix: close grpc connections after their usage is complete
  client/pkg/omnictl/internal/access/client.go
  cmd/omni/cmd/cmd.go
  internal/backend/grpc/grpc_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_bootstrap_status.go
  internal/backend/runtime/omni/controllers/omni/internal/task/clustermachine/identity.go
  internal/backend/runtime/omni/controllers/omni/machine_teardown.go
Labels: status/ok-to-test, status/ok-to-merge

#898 fix: don't forget to close grpc connections in tests
  client/pkg/client/example_test.go
  cmd/integration-test/pkg/clientconfig/clientconfig.go
  cmd/integration-test/pkg/tests/tests.go
Labels: status/ok-to-test, status/ok-to-merge

#899 fix: enable IDP initiated SAML logins
  internal/backend/saml/saml.go
Labels: status/ok-to-test, status/ok-to-merge

#906 chore: bump deps
  LICENSE
  client/go.mod
  client/go.sum
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-backups, integration/e2e-short

#908 release(v0.46.2): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#909 chore: omni enable config compression by default
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-backups, integration/e2e-short

#911 chore: omni enable config compression by default
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#912 release(0.46.3): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#921 chore: remove unused field in `s3store.Store`
  internal/backend/runtime/omni/controllers/omni/etcdbackup/store/s3store.go
  internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/s3store.go
Labels: status/ok-to-test, status/ok-to-merge

#927 fix: make the apply config fail if machine has wrong state
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#924 feat: implement secure node join flow
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/siderolink.proto
  client/api/omni/specs/siderolink_vtproto.pb.go
  client/pkg/meta/meta.go
  client/pkg/omni/resources/omni/labels.go
  client/pkg/omni/resources/siderolink/link_status.go
  client/pkg/omni/resources/siderolink/pending_machine.go
  client/pkg/omni/resources/siderolink/pending_machine_status.go
  client/pkg/omni/resources/siderolink/siderolink.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/omni/cmd/cmd.go
  frontend/src/api/omni/specs/siderolink.pb.ts
  frontend/src/api/resources.ts
  internal/backend/runtime/omni/controllers/helpers/helpers.go
  internal/backend/runtime/omni/controllers/helpers/helpers_test.go
  internal/backend/runtime/omni/controllers/omni/link_status.go
  internal/backend/runtime/omni/controllers/omni/link_status_test.go
  internal/backend/runtime/omni/controllers/omni/machine_teardown.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/controllers/omni/pending_machine_status.go
  internal/backend/runtime/omni/controllers/omni/pending_machine_status_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
  internal/pkg/config/config.go
  internal/pkg/logreceiver/logreceiver.go
  internal/pkg/logreceiver/logreceiver_test.go
  internal/pkg/siderolink/loghandler.go
  internal/pkg/siderolink/manager.go
  internal/pkg/siderolink/peers_pool.go
  internal/pkg/siderolink/peers_pool_test.go
  internal/pkg/siderolink/provision.go
  internal/pkg/siderolink/provision_test.go
  internal/pkg/siderolink/siderolink_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#933 fix: add workaround to stage upgrades for talos `v1.9.0-v1.9.2`
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
Labels: status/ok-to-test, status/ok-to-merge

#940 fix: detect more block devices
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
Labels: status/ok-to-test, status/ok-to-merge

#939 docs: how to download generic talosconfig in omnictl talosconfig help
  client/pkg/omnictl/talosconfig.go
Labels: status/ok-to-merge

#942 chore: add `compressConfigsAndMachinePatches` migration back
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#941 feat: implement the machine categories UI for the sidebar
  frontend/src/api/watch.ts
  frontend/src/components/SideBar/TSideBar.vue
  frontend/src/components/SideBar/TSideBarList.vue
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/MenuItem/TMenuItem.vue
  frontend/src/components/icons/IconMachinesAutoprovisioned.vue
  frontend/src/components/icons/IconMachinesManual.vue
  frontend/src/methods/labels.ts
  frontend/src/methods/machine.ts
  frontend/src/router/index.ts
  frontend/src/views/omni/Machines/MachineTabs.vue
  frontend/src/views/omni/Machines/Machines.vue
  frontend/src/views/omni/Machines/MachinesPending.vue
  frontend/src/views/omni/SideBar.vue
  internal/backend/runtime/omni/controllers/omni/machine.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/infraprovider/state.go
  internal/e2e-tests/main_test.go
Labels: status/ok-to-test, status/ok-to-merge

#943 feat: add a flag to enable secure join token flow
  cmd/omni/cmd/cmd.go
  internal/pkg/config/config.go
  internal/pkg/siderolink/manager.go
  internal/pkg/siderolink/provision.go
  internal/pkg/siderolink/provision_test.go
Labels: status/ok-to-test, status/ok-to-merge

#945 fix: adjust the UI layout and get rid of a couple of bugs
  frontend/src/components/SideBar/TSideBarList.vue
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/MenuItem/TMenuItem.vue
  frontend/src/components/icons/IconUpgrade.vue
  frontend/src/components/icons/IconUpgradeAvailable.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
  frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanel.vue
  frontend/src/views/cluster/Overview/components/OverviewRightPanel/OverviewRightPanelItem.vue
  frontend/src/views/omni/Machines/MachineItem.vue
  frontend/src/views/omni/Modals/ServiceAccountCreate.vue
  frontend/src/views/omni/Settings/Settings.vue
  frontend/src/views/omni/SideBar.vue
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#935 feat: push a partial config to machines in maintenance mode
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-forced-removal-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-short-secureboot-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .github/workflows/e2e-workload-proxy-cron.yaml
  .kres.yaml
  Dockerfile
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/siderolink.proto
  client/pkg/omni/resources/omni/maintenance_config_status.go
  client/pkg/omni/resources/omni/omni.go
  client/pkg/omnictl/delete.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/blocks.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  hack/test/integration.sh
  internal/backend/runtime/omni/controllers/omni/maintenance_config_status.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_status_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
Labels: status/ok-to-test, status/ok-to-merge

#946 tests: improve e2e upgrades and e2e templates tests stability
  client/go.mod
  client/go.sum
  cmd/integration-test/pkg/tests/talos.go
  cmd/integration-test/pkg/tests/template.go
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#947 release(v0.47.0-beta.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#948 fix: fix config compression migration
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#949 release(v0.47.0-beta.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#952 fix: fix bug with Omni adding machine to a cluster before upgrading
  frontend/src/views/omni/Machines/Machines.vue
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#953 release(v0.47.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#959 fix: increase log level of the SideroLink GRPC tunnel handler
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge

#951 chore: warn if cluster doesn't exist in omnictl talosconfig command
  client/pkg/omnictl/talosconfig.go
Labels: status/ok-to-merge

#957 fix: extentions list hidden on small screens
  frontend/src/views/omni/Extensions/ExtensionsPicker.vue
Labels: status/ok-to-merge

#963 chore: add logging for migrations
  internal/backend/runtime/omni/migration/manager.go
Labels: status/ok-to-test, status/ok-to-merge

#970 fix: fix exposed service links on the sidebar
  frontend/src/components/common/MenuItem/TMenuItem.vue
Labels: status/ok-to-test, status/ok-to-merge

#971 fix: disable `compressConfigsAndMachinePatches`
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#977 fix: skip applying maintenance config to unsupported machines
  internal/backend/runtime/omni/controllers/omni/maintenance_config_status.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_status_test.go
Labels: status/ok-to-test, status/ok-to-merge

#976 fix: preserve SideroLink tunnel config on machine allocation
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_vtproto.pb.go
  client/pkg/omnictl/download.go
  frontend/src/api/omni/management/management.pb.ts
  frontend/src/components/common/Checkbox/TCheckbox.vue
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
  internal/backend/grpc/schematics.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#979 chore: add `omni_machine_config_patch_size` metrics
  internal/backend/runtime/omni/controllers/omni/config_patch_metrics.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge

#980 release(v0.47.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#929 fix: enhance workloadproxy to be lazy and internally consistent
  .golangci.yml
  Makefile
  client/.golangci.yml
  cmd/integration-test/make-cookies/main.go
  cmd/omni/cmd/cmd.go
  go.mod
  go.sum
  internal/backend/runtime/omni/audit/log_file.go
  internal/backend/runtime/omni/controllers/omni/cluster_workload_proxy_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_workload_proxy_status_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/workloadproxy/healthcheck.go
  internal/backend/workloadproxy/reconcile_data.go
  internal/backend/workloadproxy/reconcile_data_test.go
  internal/backend/workloadproxy/reconcile_utils.go
  internal/backend/workloadproxy/reconciler.go
  internal/backend/workloadproxy/reconciler_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-workload-proxy

#981 chore: expose `omni_runtime_cached_resources` metric
  go.mod
  go.sum
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge
