Repository siderolabs/omni, pull requests merged in 2025-10, with the labels that each got.

#1672 backports: for v1.2.1
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#1673 release(v1.2.1): prepare release
  CHANGELOG.md
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1675 refactor(msw): simplify msw handlers in storybook
  frontend/.storybook/preview.ts
  frontend/msw/helpers.ts
  frontend/msw/server.ts
  frontend/src/api/watch.spec.ts
  frontend/src/views/omni/Extensions/ExtensionsPicker.stories.ts
  frontend/src/views/omni/Machines/MachinesPending.stories.ts
  frontend/src/views/omni/Modals/MaintenanceUpdate.stories.ts
  frontend/src/views/omni/Modals/UpdateKubernetes.stories.ts
  frontend/src/views/omni/Modals/UpdateTalos.stories.ts
Labels: status/ok-to-test, status/ok-to-merge

#1680 fix(frontend): fix locked icon not showing when cluster is locked
  frontend/msw/server.ts
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/icons/IconLocked.vue
  frontend/src/components/icons/IconUnlocked.vue
  frontend/src/router/index.ts
  frontend/src/views/cluster/Nodes/NodeMounts.vue
  frontend/src/views/omni/Clusters/ClusterItem.spec.ts
  frontend/src/views/omni/Clusters/ClusterItem.vue
  frontend/vitest.setup.ts
Labels: status/ok-to-test, status/ok-to-merge

#1682 fix(frontend): fix alignment of provisioning machines
  frontend/src/views/cluster/ClusterMachines/ClusterMachines.vue
  frontend/src/views/cluster/ClusterMachines/MachineRequest.vue
  frontend/src/views/cluster/ClusterMachines/MachineSet.vue
  frontend/src/views/omni/Clusters/ClusterItem.vue
  frontend/src/views/omni/Clusters/Clusters.stories.ts
  frontend/src/views/omni/Clusters/Clusters.vue
Labels: status/ok-to-test, status/ok-to-merge

#1690 refactor: use TalosVersion compatibility in Kubernetes upgrades
  internal/backend/runtime/omni/controllers/omni/internal/kubernetes/versions.go
  internal/backend/runtime/omni/controllers/omni/internal/kubernetes/versions_test.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_upgrade_status.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-upgrades

#1691 feat(frontend): add stripe link to settings sidebar
  client/api/common/omni.pb.go
  client/api/omni/management/management.pb.go
  client/api/omni/oidc/oidc.pb.go
  client/api/omni/resources/resources.pb.go
  client/api/omni/specs/auth.pb.go
  client/api/omni/specs/ephemeral.pb.go
  client/api/omni/specs/infra.pb.go
  client/api/omni/specs/oidc.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/system.pb.go
  client/api/omni/specs/virtual.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/components/SideBar/TSideBarList.vue
  frontend/src/components/common/MenuItem/TMenuItem.vue
  frontend/src/methods/cluster.spec.ts
  frontend/src/methods/features.ts
  frontend/src/views/cluster/Overview/components/OverviewContent.vue
  frontend/src/views/cluster/SideBar.vue
  frontend/src/views/omni/Clusters/ClusterWorkloadProxyingCheckbox.vue
  frontend/src/views/omni/SideBar.vue
  internal/pkg/features/features.go
Labels: status/ok-to-test, status/ok-to-merge

#1677 Fix: Typo in Helm chart readme service name for API Ingress example
  deploy/helm/README.md
Labels: status/ok-to-merge
