Repository siderolabs/omni, pull requests merged in 2025-05, with the labels that each got.

#1163 fix: use the correct sort order for the automatic install disk selection
  internal/backend/runtime/omni/controllers/omni/machine_config_gen_options.go
  internal/backend/runtime/omni/controllers/omni/machine_config_gen_options_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1164 feat: update machinery and specs to Talos 1.10.0
  .kres.yaml
  Dockerfile
  Makefile
  client/api/common/common.proto
  client/api/talos/machine/machine.pb.gw.go
  client/api/talos/machine/machine.proto
  frontend/src/api/common/common.pb.ts
  frontend/src/api/common/common.proto
  frontend/src/api/talos/machine/machine.pb.ts
  frontend/src/api/talos/machine/machine.proto
  frontend/src/schemas/config.schema.json
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1174 fix: correctly encode exposed service redirect URL after auth
  .golangci.yml
  client/.golangci.yml
  frontend/src/views/omni/Auth/Authenticate.vue
Labels: status/ok-to-test, status/ok-to-merge

#1175 fix: gracefully render exposed services errors
  frontend/src/views/cluster/ExposedService/ExposedServiceSideBar.vue
Labels: status/ok-to-test, status/ok-to-merge

#1176 chore: update JS deps, drop `package-lock.json`
  frontend/.gitignore
  frontend/bun.lock
  frontend/package-lock.json
  frontend/package.json
Labels: status/ok-to-test, status/ok-to-merge

#1177 release(v0.49.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1178 test: bump Talemu tests timeout
  cmd/integration-test/pkg/tests/talos.go
  hack/test/integration.sh
Labels: status/ok-to-test, status/ok-to-merge

#1182 fix: use the correct res order for the cluster operations in the UI
  frontend/src/components/common/Form/JsonForm.vue
  frontend/src/states/cluster-management/index.ts
  frontend/test/unit/clusterManageState.spec.ts
  frontend/test/unit/watch.spec.ts
Labels: status/ok-to-test, status/ok-to-merge

#1186 feat(ci): support releasing helm charts
  .github/workflows/helm.yaml
  .kres.yaml
  Dockerfile
  Makefile
  deploy/helm/omni/Chart.yaml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#1183 release(v0.49.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1187 chore: bump Go deps
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  go.work
  hack/zstd-dict/go.mod
  hack/zstd-dict/go.sum
  internal/backend/runtime/omni/audit/state.go
  internal/e2e-tests/go.mod
  internal/e2e-tests/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#1190 fix: fix crash in the SAML ACS handler
  internal/backend/saml/saml.go
Labels: status/ok-to-test, status/ok-to-merge

#1191 release(v0.49.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1195 fix: keep ClusterUUID resource alive until the cluster is destroyed
  internal/backend/runtime/omni/controllers/omni/cluster.go
  internal/backend/runtime/omni/controllers/omni/cluster_uuid.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1199 fix: remove deprecated controller finalizers from the machine classes
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#1202 fix: update go-kubernetes library to the latest version
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#1184 test: add unit test for nextAvailableClusterName function
  frontend/test/unit/methods/cluster.spec.ts
Labels: status/ok-to-merge

#1204 chore: introduce COSI state helpers to reduce boiler plate code count
  client/go.mod
  client/go.sum
  client/pkg/cosi/helpers/helpers.go
  client/pkg/cosi/helpers/teardown.go
  client/pkg/cosi/helpers/teardown_test.go
  client/pkg/infra/controllers/provision.go
  cmd/integration-test/pkg/tests/tests.go
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/helpers/helpers.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_request_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_teardown.go
  internal/backend/runtime/omni/controllers/omni/config_patch_cleanup.go
  internal/backend/runtime/omni/controllers/omni/control_plane_status.go
  internal/backend/runtime/omni/controllers/omni/discovery_affiliate_delete_task.go
  internal/backend/runtime/omni/controllers/omni/discovery_affiliate_delete_task_test.go
  internal/backend/runtime/omni/controllers/omni/infra_machine.go
  internal/backend/runtime/omni/controllers/omni/infra_provider_config_patch.go
  internal/backend/runtime/omni/controllers/omni/internal/mappers/mappers.go
  internal/backend/runtime/omni/controllers/omni/kubeconfig.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_status.go
  internal/backend/runtime/omni/controllers/omni/kubernetes_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/machine_request_set_status.go
  internal/backend/runtime/omni/controllers/omni/machine_request_set_status_test.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_link.go
  internal/backend/runtime/omni/controllers/omni/machine_status_snapshot.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/controllers/omni/talosconfig.go
  internal/backend/runtime/omni/migration/deprecated_resources_test.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1149 test: bump Talos version used in integration tests to `v1.10`
  client/pkg/constants/constants.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/integration-test/pkg/tests/template.go
  cmd/integration-test/pkg/tests/tests.go
  frontend/src/api/resources.ts
  hack/test/integration.sh
  internal/pkg/constants/versions.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1207 fix: pin AWS s3 libs version to 1.72.3
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/etcdbackup/store/s3store.go
Labels: status/ok-to-test, status/ok-to-merge

#1208 release(v0.50.0-beta.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1209 fix: do not show some menu elements for Reader users in the UI
  frontend/src/methods/auth.ts
  frontend/src/views/cluster/Nodes/NodeExtensions.vue
  frontend/src/views/common/NodeContextMenu.vue
  internal/backend/runtime/omni/virtual/state.go
Labels: status/ok-to-test, status/ok-to-merge

#1213 fix: make cluster validations consistent between templates and UI
  client/pkg/omni/resources/omni/cluster.go
  client/pkg/template/internal/models/cluster.go
  client/pkg/template/template_test.go
  client/pkg/template/testdata/cluster1-resources.yaml
  client/pkg/template/testdata/cluster1.yaml
  internal/backend/runtime/omni/state_validation.go
Labels: status/ok-to-test, status/ok-to-merge

#1214 fix: use the correct schematic IP for maintenance upgrades
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-forced-removal-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-short-secureboot-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .github/workflows/e2e-workload-proxy-cron.yaml
  .kres.yaml
  Dockerfile
  Makefile
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.pb.gw.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_grpc.pb.go
  client/api/omni/management/management_vtproto.pb.go
  cmd/integration-test/pkg/root.go
  cmd/integration-test/pkg/tests/blocks.go
  cmd/integration-test/pkg/tests/cluster.go
  cmd/integration-test/pkg/tests/stats.go
  cmd/integration-test/pkg/tests/talos.go
  cmd/integration-test/pkg/tests/tests.go
  deploy/helm/omni/Chart.yaml
  frontend/src/api/omni/management/management.pb.ts
  frontend/src/methods/machine.ts
  frontend/src/views/omni/Modals/MaintenanceUpdate.vue
  hack/test/integration.sh
  internal/backend/grpc/management.go
  internal/backend/imagefactory/client.go
  internal/backend/installimage/installimage.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/omni.go
  internal/pkg/constants/versions.go
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-upgrades

#1215 release(v0.50.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1219 test: use latest Talemu infra provider version in the integration tests
  hack/test/integration.sh
Labels: status/ok-to-test, status/ok-to-merge

#1224 fix: properly detect infra provider service accounts
  client/pkg/access/serviceaccount.go
  internal/backend/runtime/omni/controllers/omni/service_account_status.go
  internal/backend/runtime/omni/controllers/omni/service_account_status_test.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#1230 fix: make sure `powering on` stage is correctly set on infra machines
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  internal/backend/powerstage/watcher.go
  internal/backend/powerstage/watcher_test.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/controllers/omni/internal/talos/schematic.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/machine_status_test.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_status.go
  internal/backend/runtime/omni/omni.go
Labels: status/ok-to-test, status/ok-to-merge

#1231 Create SECURITY.md
  SECURITY.md
Labels: status/ok-to-test, status/ok-to-merge

#1232 fix: fix nil dereference in machine status controller
  internal/backend/runtime/omni/controllers/omni/machine_status.go
Labels: status/ok-to-test, status/ok-to-merge

#1236 chore: allow running Omni programmatically from other Go code
  cmd/omni/cmd/cmd.go
  cmd/omni/cmd/run.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge
