Repository siderolabs/omni, pull requests merged in 2025-07, with the labels that each got.

#1299 fix: update SAML library to the forked version with the ACS parser fix
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#1316 release(v0.52.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1304 fix: gracefully handle logServer shutdown
  internal/pkg/logreceiver/logreceiver.go
  internal/pkg/siderolink/manager.go
Labels: status/ok-to-test, status/ok-to-merge

#1318 test: reduce the log verbosity in unit tests
  Dockerfile
  internal/backend/grpc/configs_test.go
  internal/backend/grpc/grpc_test.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/omni_test.go
  internal/backend/runtime/omni/talosconfig_test.go
  internal/backend/runtime/talos/clients_test.go
  internal/pkg/siderolink/provision_test.go
  internal/pkg/siderolink/siderolink_test.go
Labels: status/ok-to-merge

#1339 fix: do not filter out noop events in the infra provider state
  internal/backend/runtime/omni/infraprovider/state.go
  internal/backend/runtime/omni/infraprovider/state_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1342 feat: implement the API for reading resources and their dependency graph
  .dockerignore
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-cluster-import-cron.yaml
  .github/workflows/e2e-forced-removal-cron.yaml
  .github/workflows/e2e-omni-upgrade-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-short-secureboot-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .github/workflows/e2e-workload-proxy-cron.yaml
  .github/workflows/helm.yaml
  .github/workflows/lock.yml
  .github/workflows/slack-notify.yaml
  .github/workflows/stale.yml
  .golangci.yml
  Dockerfile
  Makefile
  client/.golangci.yml
  client/api/omni/management/management.pb.gw.go
  client/api/omni/resources/resources.pb.go
  client/api/omni/resources/resources.pb.gw.go
  client/api/omni/resources/resources.proto
  client/api/omni/resources/resources_grpc.pb.go
  client/api/omni/resources/resources_vtproto.pb.go
  client/pkg/omni/resources/omni/omni.go
  frontend/src/api/omni/resources/resources.pb.ts
  frontend/src/api/resources.ts
  internal/backend/grpc/dependency_graph.go
  internal/backend/grpc/grpc.go
  internal/backend/grpc/resource.go
  internal/backend/server.go
Labels: status/ok-to-test, status/ok-to-merge

#1354 fix: allow encoding join tokens using v1 version
  client/pkg/infra/controllers/provision.go
  client/pkg/infra/infra.go
  client/pkg/infra/infra_test.go
  client/pkg/jointoken/jointoken.go
  client/pkg/jointoken/jointoken_test.go
  client/pkg/siderolink/siderolink.go
  internal/backend/runtime/omni/controllers/omni/provider_join_config_test.go
  internal/pkg/siderolink/provision.go
  internal/pkg/siderolink/provision_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1355 chore: support encoding extra docs in `siderolink.RenderJoinConfig`
  client/pkg/siderolink/siderolink.go
  client/pkg/siderolink/siderolink_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1356 fix: ignore `MachineStatus` having no TalosVersion in DNS service
  internal/backend/dns/service.go
Labels: status/ok-to-merge

#1361 release(v1.0.0-beta.1): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1364 test: allow ignoring unknown config fields in the integration test
  internal/backend/runtime/omni/migration/migrations.go
  internal/integration/integration_test.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#1363 release(v1.0.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-merge, integration/e2e

#1373 fix: properly handle empty configs in `omnictl config merge` CLI command
  client/pkg/omnictl/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#1367 fix: remove MachineLabels when a Link is removed
  internal/backend/runtime/omni/controllers/omni/link_cleanup.go
  internal/backend/runtime/omni/controllers/omni/link_cleanup_test.go
Labels: status/ok-to-test, status/ok-to-merge
