Repository siderolabs/omni, pull requests merged in 2025-08, with the labels that each got.

#1393 chore: run rekres
  .github/workflows/slack-notify.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1395 fix: install frontend dependencies from lockfile
  .dockerignore
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge

#1400 fix: stop enforcing talos version check on machine allocation
  frontend/src/views/omni/Clusters/Management/ClusterCreate.vue
  frontend/src/views/omni/Clusters/Management/ClusterScale.vue
  internal/backend/runtime/omni/state_validation.go
Labels: status/ok-to-test, status/ok-to-merge

#1403 chore: remove unused .eslintrc.yaml config
  frontend/.eslintrc.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1417 fix: prevent service account creation if name is already in use
  internal/backend/grpc/serviceaccount.go
  internal/integration/auth_test.go
  internal/pkg/auth/serviceaccount/serviceaccount.go
Labels: status/ok-to-test, status/ok-to-merge

#1422 fix: incorrect disabled icon color 
  frontend/src/components/icons/IconKubernetes.vue
Labels: status/ok-to-test, status/ok-to-merge

#1425 chore: commit vscode settings for frontend
  frontend/.gitignore
  frontend/.vscode/extensions.json
  frontend/.vscode/settings.json
Labels: status/ok-to-test, status/ok-to-merge

#1429 chore: prepare omni for talos v1.11.0-beta.2
  .kres.yaml
  Dockerfile
  Makefile
  client/api/talos/machine/machine.pb.gw.go
  client/api/talos/machine/machine.proto
  client/go.mod
  client/go.sum
  frontend/src/api/talos/machine/machine.pb.ts
  frontend/src/api/talos/machine/machine.proto
  frontend/src/schemas/config.schema.json
  go.mod
  go.sum
  internal/integration/auth_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1436 chore: update frontend dependencies
  frontend/.vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/methods/index.ts
  frontend/src/views/cluster/Nodes/NodeOverview.vue
  frontend/src/views/cluster/Nodes/NodesList.vue
  frontend/src/views/cluster/Nodes/components/NodesItem.vue
  frontend/src/views/cluster/Pods/components/TPodsItem.vue
  frontend/src/views/cluster/Pods/components/TPodsList.vue
  frontend/src/views/omni/Modals/DownloadSupportBundle.vue
Labels: status/ok-to-test, status/ok-to-merge

#1440 feat: change default location for storing Omni config and user PGP keys
  client/go.mod
  client/go.sum
  client/pkg/client/client.go
  client/pkg/client/options.go
  client/pkg/omnictl/config/config.go
  client/pkg/omnictl/download.go
  client/pkg/omnictl/internal/access/client.go
  client/pkg/omnictl/internal/access/flags.go
  client/pkg/omnictl/root.go
  go.mod
  go.sum
  internal/backend/grpc/configs_test.go
  internal/integration/cli_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1448 chore: rekres, bump deps, Go (to 1.25), satisfy linters
  .dockerignore
  .github/workflows/ci.yaml
  .github/workflows/e2e-backups-cron.yaml
  .github/workflows/e2e-cluster-import-cron.yaml
  .github/workflows/e2e-forced-removal-cron.yaml
  .github/workflows/e2e-omni-upgrade-cron.yaml
  .github/workflows/e2e-scaling-cron.yaml
  .github/workflows/e2e-short-cron.yaml
  .github/workflows/e2e-short-secureboot-cron.yaml
  .github/workflows/e2e-templates-cron.yaml
  .github/workflows/e2e-upgrades-cron.yaml
  .github/workflows/e2e-workload-proxy-cron.yaml
  .github/workflows/helm.yaml
  .vscode/settings.json
  Dockerfile
  Makefile
  client/api/common/omni.pb.go
  client/api/omni/management/management.pb.go
  client/api/omni/oidc/oidc.pb.go
  client/api/omni/resources/resources.pb.go
  client/api/omni/specs/auth.pb.go
  client/api/omni/specs/ephemeral.pb.go
  client/api/omni/specs/infra.pb.go
  client/api/omni/specs/oidc.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/system.pb.go
  client/api/omni/specs/virtual.pb.go
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  go.work
  hack/govulncheck.sh
  hack/zstd-dict/go.mod
  hack/zstd-dict/go.sum
  internal/backend/grpc/configs_test.go
  internal/backend/grpc/grpc_test.go
  internal/backend/grpc/router/talos_backend_test.go
  internal/backend/grpc/schematics_test.go
  internal/backend/resourcelogger/resourcelogger_test.go
  internal/backend/runtime/omni/controllers/omni/config_patch_cleanup_test.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration_test.go
  internal/backend/runtime/omni/controllers/omni/talos_extensions_test.go
  internal/backend/server.go
  internal/e2e-tests/Dockerfile
  internal/e2e-tests/go.mod
  internal/e2e-tests/go.sum
  internal/pkg/grpcutil/logger_test.go
  internal/pkg/logreceiver/logreceiver.go
  internal/pkg/siderolink/manager.go
  internal/pkg/siderolink/siderolink_test.go
  internal/pkg/test/grpc.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1467 release(v1.1.0-beta.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1278 feat: add jitter and lazy health checks to exposed services
  cmd/omni/cmd/cmd.go
  cmd/omni/pkg/app/app.go
  go.mod
  go.sum
  hack/test/integration.sh
  internal/backend/grpc/grpc_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/omni_test.go
  internal/backend/runtime/omni/talosconfig_test.go
  internal/backend/services/workloadproxy/reconciler.go
  internal/backend/services/workloadproxy/reconciler_test.go
  internal/backend/workloadproxy/lb/lazy.go
  internal/backend/workloadproxy/lb/lb.go
  internal/backend/workloadproxy/lb/probe_all.go
  internal/backend/workloadproxy/lb/probe_windows.go
  internal/pkg/config/config.go
  internal/pkg/config/services.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-workload-proxy

#1463 chore: improve useWatch typings
  frontend/src/api/watch.ts
  frontend/src/components/common/OngoingTasks/OngoingTasks.vue
  frontend/src/components/common/Watch/Watch.vue
  frontend/src/components/common/Watch/useWatch.ts
  frontend/src/views/cluster/Backups/BackupsList.vue
  frontend/src/views/cluster/ClusterMachines/ClusterMachines.vue
  frontend/src/views/cluster/Nodes/NodePatches.vue
  frontend/src/views/cluster/Pods/TPods.vue
  frontend/src/views/omni/Clusters/Clusters.vue
  frontend/src/views/omni/Clusters/Management/ClusterScale.vue
  frontend/src/views/omni/Extensions/ExtensionsPicker.vue
  frontend/src/views/omni/MachineClasses/MachineClass.vue
  frontend/src/views/omni/Machines/Machines.vue
  frontend/src/views/omni/Modals/NodeDestroyCancel.vue
  frontend/src/views/omni/Modals/RoleEdit.vue
  frontend/src/views/omni/Overview/Overview.vue
Labels: status/ok-to-test, status/ok-to-merge

#1445 feat: home page redesign
  frontend/src/components/common/Card/Card.vue
  frontend/src/components/common/Charts/RadialBar.vue
  frontend/src/components/common/Watch/Watch.vue
  frontend/src/index.css
  frontend/src/router/index.ts
  frontend/src/views/cluster/ClusterMachines/ClusterMachines.vue
  frontend/src/views/cluster/Overview/components/OverviewCircleChart/OverviewCircleChart.vue
  frontend/src/views/cluster/Overview/components/OverviewCircleChart/OverviewCircleChartItem.vue
  frontend/src/views/cluster/Overview/components/OverviewContent.vue
  frontend/src/views/cluster/Pods/TPods.vue
  frontend/src/views/omni/Clusters/ClusterStatus.vue
  frontend/src/views/omni/Clusters/Management/ClusterScale.vue
  frontend/src/views/omni/Extensions/ExtensionsPicker.vue
  frontend/src/views/omni/Home/Home.vue
  frontend/src/views/omni/Home/HomeClustersChart.vue
  frontend/src/views/omni/Home/HomeContent.vue
  frontend/src/views/omni/Home/HomeGeneralInformation.vue
  frontend/src/views/omni/Home/HomeGeneralInformationCopyable.vue
  frontend/src/views/omni/Home/HomeMachinesChart.vue
  frontend/src/views/omni/Home/HomeNoAccess.vue
  frontend/src/views/omni/Home/HomeRecentClusters.vue
  frontend/src/views/omni/Home/HomeRecentMachines.vue
  frontend/src/views/omni/Machines/Machines.vue
  frontend/src/views/omni/Modals/RoleEdit.vue
  frontend/src/views/omni/Overview/Overview.vue
  frontend/src/views/omni/SideBar.vue
  internal/e2e-tests/main_test.go
Labels: status/ok-to-test, status/ok-to-merge, UI

#1477 release(v1.1.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1480 chore: use vue specific rules for dot-notation and eqeqeq
  frontend/eslint.config.ts
  frontend/src/components/common/TInput/TInput.vue
Labels: status/ok-to-test, status/ok-to-merge

#1485 release(v1.1.1): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  deploy/helm/omni/Chart.yaml
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge
