Repository siderolabs/omni, pull requests merged in 2025-04, with the labels that each got.

#1058 fix: restore timeout in `OmniSuite.SetupTest`
  internal/backend/runtime/omni/controllers/omni/config_patch_cleanup_test.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1061 release(v0.48.0-beta.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1062 chore: change upload and download limits flags to mbps
  cmd/omni/cmd/cmd.go
  hack/release.toml
  internal/backend/runtime/omni/controllers/omni/cluster_bootstrap_status_test.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup_mock_2_test.go
  internal/backend/runtime/omni/controllers/omni/etcdbackup/store/disabledstore.go
  internal/backend/runtime/omni/controllers/omni/etcdbackup/store/filestore.go
  internal/backend/runtime/omni/controllers/omni/etcdbackup/store/metrics.go
  internal/backend/runtime/omni/controllers/omni/etcdbackup/store/s3store.go
  internal/backend/runtime/omni/controllers/omni/etcdbackup/store/store.go
  internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/s3store.go
  internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/s3store_test.go
  internal/backend/runtime/omni/controllers/omni/secrets_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_validation_test.go
  internal/pkg/config/config.go
Labels: status/ok-to-test, status/ok-to-merge

#1067 release(v0.48.0): prepare release
  .kres.yaml
  CHANGELOG.md
  LICENSE
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1071 fix: use proper background for the sticky window in the code editor
  frontend/src/components/common/CodeEditor/CodeEditor.vue
  frontend/src/views/cluster/ClusterMachines/ClusterMachine.vue
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#1077 fix: revert workload proxy LB refactoring
  .golangci.yml
  client/.golangci.yml
  cmd/omni/cmd/cmd.go
  go.mod
  go.sum
  internal/backend/runtime/omni/controllers/omni/cluster_workload_proxy_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_workload_proxy_status_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/workloadproxy/healthcheck.go
  internal/backend/workloadproxy/reconcile_data.go
  internal/backend/workloadproxy/reconcile_data_test.go
  internal/backend/workloadproxy/reconcile_utils.go
  internal/backend/workloadproxy/reconciler.go
  internal/backend/workloadproxy/reconciler_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-workload-proxy

#1079 fix: mark all exposed services to have a non-explicit alias
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/exposed_service.go
  frontend/src/api/omni/specs/omni.pb.ts
  internal/backend/runtime/omni/controllers/omni/internal/exposedservice/reconciler.go
Labels: status/ok-to-test, status/ok-to-merge

#1082 fix: fix existing alias check for exposed services
  cmd/integration-test/pkg/tests/workload_proxy.go
  internal/backend/runtime/omni/controllers/omni/internal/exposedservice/reconciler.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-workload-proxy

#1083 release(v0.48.1): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#1094 fix: config patch cleanup
  internal/backend/runtime/omni/controllers/omni/config_patch_cleanup.go
  internal/backend/runtime/omni/controllers/omni/config_patch_cleanup_test.go
  internal/backend/runtime/omni/controllers/omni/internal/configpatch/configpatch.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1100 fix: create config patches to prevent reboot on version contract revert
  internal/backend/runtime/omni/migration/manager.go
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#1098 fix: use correct version contract for machine config generation
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1108 release(v0.48.2): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#1111 fix: properly skip the contract config patch removal migration
  internal/backend/runtime/omni/migration/migration_test.go
  internal/backend/runtime/omni/migration/migrations.go
Labels: status/ok-to-test, status/ok-to-merge

#1113 release(v0.48.3): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#1122 feat: improve logging/debugging of exposed services
  internal/backend/grpc/support.go
  internal/backend/workloadproxy/handler.go
Labels: status/ok-to-test, status/ok-to-merge

#1109 fix: move JSON schema forms validation to backend
  client/api/omni/management/management.pb.go
  client/api/omni/management/management.pb.gw.go
  client/api/omni/management/management.proto
  client/api/omni/management/management_grpc.pb.go
  client/api/omni/management/management_vtproto.pb.go
  client/api/omni/specs/omni.pb.go
  frontend/src/api/omni/management/management.pb.ts
  frontend/src/components/common/Form/JsonForm.vue
  frontend/src/views/omni/MachineClasses/MachineClass.vue
  internal/backend/grpc/grpc.go
  internal/backend/grpc/management.go
  internal/backend/grpc/validate.go
  internal/backend/runtime/omni/state_validation.go
  internal/pkg/jsonschema/jsonschema.go
Labels: status/ok-to-test, status/ok-to-merge

#1126 fix: correctly sort versions on the download installation media page
  frontend/src/views/omni/Modals/DownloadInstallationMedia.vue
Labels: status/ok-to-test, status/ok-to-merge

#1127 fix: return proper errors for the SideroLink provision API
  internal/pkg/siderolink/provision.go
Labels: status/ok-to-test, status/ok-to-merge

#1128 chore: rekres, bump deps, satisfy linters, fix generated test headers
  .golangci.yml
  Dockerfile
  Makefile
  client/.golangci.yml
  client/api/common/omni.pb.go
  client/api/omni/management/management.pb.go
  client/api/omni/oidc/oidc.pb.go
  client/api/omni/resources/resources.pb.go
  client/api/omni/specs/auth.pb.go
  client/api/omni/specs/ephemeral.pb.go
  client/api/omni/specs/infra.pb.go
  client/api/omni/specs/oidc.pb.go
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/siderolink.pb.go
  client/api/omni/specs/system.pb.go
  client/api/omni/specs/virtual.pb.go
  client/go.mod
  client/go.sum
  client/pkg/cosi/labels/labels_test.go
  client/pkg/omnictl/download.go
  client/pkg/omnictl/kubeconfig.go
  client/pkg/omnictl/talosconfig.go
  client/pkg/template/internal/models/cluster.go
  client/pkg/template/internal/models/machine.go
  cmd/integration-test/pkg/tests/cli.go
  cmd/integration-test/pkg/tests/image.go
  cmd/integration-test/pkg/tests/kubernetes.go
  frontend/src/api/omni/management/management.pb.ts
  go.mod
  go.sum
  internal/backend/grpc/export_test.go
  internal/backend/grpc/schematics.go
  internal/backend/oidc/internal/client/client.go
  internal/backend/runtime/omni/audit/log_file_test.go
  internal/backend/runtime/omni/audit/walk_test.go
  internal/backend/runtime/omni/controllers/omni/config_patch_cleanup_test.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup_mock_2_test.go
  internal/backend/runtime/omni/controllers/omni/etcd_backup_test.go
  internal/backend/runtime/omni/controllers/omni/etcdbackup/etcdbackup_test.go
  internal/backend/runtime/omni/controllers/omni/internal/etcdbackup/s3store/export_test.go
  internal/backend/runtime/omni/controllers/omni/internal/machineset/operations_test.go
  internal/backend/runtime/omni/controllers/omni/internal/task/clustermachine/identity.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/controllers/omni/maintenance_config_status.go
  internal/backend/runtime/runtime.go
  internal/backend/saml/session_test.go
  internal/pkg/auth/constants.go
  internal/pkg/compress/compress.go
Labels: status/ok-to-test, status/ok-to-merge

#1147 fix: do not add omni api host to kube-apiserver cert SANs
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
Labels: status/ok-to-test, status/ok-to-merge

#1150 test: fix the flaky key storage test
  internal/backend/oidc/internal/storage/keys/storage_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1145 test: add config encoding stability tests
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1073 feat: allow force-destroying a node in booting state
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/common/common.go
  client/pkg/omni/resources/omni/node_force_destroy_request.go
  client/pkg/omni/resources/omni/omni.go
  client/pkg/omnictl/cluster/machine.go
  client/pkg/omnictl/common.go
  client/pkg/omnictl/delete.go
  client/pkg/omnictl/get.go
  client/pkg/omnictl/omnictl.go
  client/pkg/omnictl/resources/destroy.go
  client/pkg/omnictl/resources/resources.go
  cmd/integration-test/pkg/tests/auth.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  frontend/src/methods/cluster.ts
  frontend/src/views/omni/Modals/NodeDestroy.vue
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/export_test.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1138 feat: implement async delete from discovery service(s)
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/omni/resources/omni/cluster_machine_identity.go
  client/pkg/omni/resources/omni/discovery_affiliate_delete_task.go
  client/pkg/omni/resources/omni/omni.go
  cmd/integration-test/pkg/tests/auth.go
  cmd/omni/cmd/cmd.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/api/resources.ts
  internal/backend/discovery/clientcache.go
  internal/backend/discovery/internal/discovery/client.go
  internal/backend/grpc/configs_test.go
  internal/backend/grpc/grpc_test.go
  internal/backend/grpc/support.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_identity.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_teardown.go
  internal/backend/runtime/omni/controllers/omni/discovery_affiliate_delete_task.go
  internal/backend/runtime/omni/controllers/omni/discovery_affiliate_delete_task_test.go
  internal/backend/runtime/omni/controllers/omni/internal/task/clustermachine/identity.go
  internal/backend/runtime/omni/omni.go
  internal/backend/runtime/omni/omni_test.go
  internal/backend/runtime/omni/state_access.go
  internal/backend/runtime/omni/talosconfig_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e-scaling, integration/e2e-short, integration/e2e-forced-removal

#1152 fix: sort Talos versions by semver on the cluster creation screen
  frontend/src/views/omni/Clusters/Management/ClusterCreate.vue
Labels: status/ok-to-test, status/ok-to-merge

#1146 fix: remove "Generated by Omni..." comment from machine config
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status.go
Labels: status/ok-to-test, status/ok-to-merge, integration/e2e

#1153 fix: disable Talos >= 1.10 for now as Omni isn't ready for it yet
  internal/backend/runtime/omni/controllers/omni/versions.go
  internal/pkg/constants/versions.go
Labels: status/ok-to-test, status/ok-to-merge

#1159 release(v0.48.4): prepare release
  CHANGELOG.md
  hack/release.toml
  internal/version/data/tag
Labels: status/ok-to-test, status/ok-to-merge

#1161 fix: remove machine set allocation source option
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  client/pkg/template/internal/models/machineset.go
  client/pkg/template/operations/export.go
  client/pkg/template/operations/testdata/export/cluster-resources.yaml
  client/pkg/template/testdata/cluster3-resources.yaml
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/states/cluster-management/index.ts
  frontend/src/views/omni/Clusters/Management/MachineSetConfig.vue
  frontend/test/unit/clusterManageState.spec.ts
  internal/backend/runtime/omni/controllers/omni/machine_provision.go
  internal/backend/runtime/omni/controllers/omni/machine_set_node.go
  internal/backend/runtime/omni/state_validation.go
  internal/backend/runtime/omni/state_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge

#1162 fix: collect and handle UKI boot information
  client/api/omni/specs/omni.pb.go
  client/api/omni/specs/omni.proto
  client/api/omni/specs/omni_vtproto.pb.go
  frontend/src/api/omni/specs/omni.pb.ts
  frontend/src/views/cluster/Nodes/NodeOverview.vue
  frontend/src/views/omni/Machines/MachineItem.vue
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config.go
  internal/backend/runtime/omni/controllers/omni/cluster_machine_config_status_test.go
  internal/backend/runtime/omni/controllers/omni/infra_machine.go
  internal/backend/runtime/omni/controllers/omni/infra_machine_test.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/machine.go
  internal/backend/runtime/omni/controllers/omni/internal/task/machine/poll.go
  internal/backend/runtime/omni/controllers/omni/machine_config_gen_options.go
  internal/backend/runtime/omni/controllers/omni/machine_status.go
  internal/backend/runtime/omni/controllers/omni/omni_test.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration.go
  internal/backend/runtime/omni/controllers/omni/schematic_configuration_test.go
  internal/backend/runtime/omni/controllers/omni/talos_upgrade_status.go
  internal/backend/runtime/omni/migration/migration_test.go
Labels: status/ok-to-test, status/ok-to-merge
